### ISSUE TITLE
Add many2one field to paramater

### ISSUE THREAD

**Issue by tomykho** [WilldooIT/Pentaho-reports-for-OpenERP#111]
Can you add many2one field for this addon?
Because sometime we want to filter large data (ex: Customer), it is consume too much time to wait if we use selection.

**Comment by richard-willdooit** [comment]
@claudkho 
Could you be more specific?  Is this an object or sql based report?  Object based reports provide a lot of support for many2one fields.

Are you talking about filtering the customer before calling the report?

Please elaborate as I am unsure of what your question is relating to.

Richard

**Comment by tomykho** [comment]
@richard-willowit 
Actually i want to have many2one filter on pentaho wizard at OpenERP.
So, if i want to filter customer, so only set the parameter relation to res.partner and specify the domain and the wizard will have many2one field for filtering Customer.
Is there a way to do that?

**Comment by richard-willdooit** [comment]
@claudkho 

I am still a bit unclear.

If you define a parameter for the partner_id, for example, and provide it a datasource, then that will put partner on a wizard for selection before running the report.

Have you seen the youtube videos - video 5 here has the method: http://www.youtube.com/user/WillowITMedia

**Comment by tomykho** [comment]
@richard-willowit 

Yeah, currently we are already using selection.
That's why in my first comment:

> Because sometime we want to filter large data (ex: Customer), it is consume too much time to wait if we use selection.

And we need to wait about 1-2 min for the wizard to prompt out.

We gained the performance by changing the selection to many2one fields for OpenERP 6.0 by customized your addon, but i hope you can help me to add this new feature in future release.

Regards,

Tomy Kho

**Comment by richard-willdooit** [comment]
@claudkho 

Could you send me the changes you made, or a diff, for what you did in version 6?

I am still unclear, as the selection list for the partners can be based on a query which can be smart enough to limit the number of partners returned.  If that query returns a large or small number of partners, then that will affect performance of the wizard, but I think you are wanting to pre-reduce the number of partners, and I do not quite see where the performance improvement would come.

I am keen to see what you mean so would love to see a code snippet or diff file

**Comment by richard-willdooit** [comment]
@claudkho I am still waiting to hear back about what this entailed.

**Comment by tomykho** [comment]
I am very sorry @richard-willowit , I stopped working at my previous company which using your addons, So currently i don't have any code snippet on their customized addons.

Regards,

Tomy Kho
