### ISSUE TITLE
Printing issue: print only the first record

### ISSUE THREAD

**Issue by soukainasb** [WilldooIT/Pentaho-reports-for-OpenERP#112]
I followed all steps during installation and eveything is working fine.the only issue i get is:
Suppose we have 3 records in my DataBase,weither i select the first one or the second or whatever, when i click on print,i always get the first record printed and not the one selected.
Could you help me please,is it some bug or did i do something wrong?
Im using Openerp 7.0 and PRD 3.9.1

Thank you

**Comment by kazuyahiko** [comment]
did you use filter?
if you did don't forget to put your parameter filter in the datasource,

didlook 
Pada Jumat, 9 Mei 2014 21:10, soukainasb notifications@github.com menulis:

I followed all steps during installation and eveything is working fine.the only issue i get is:
Suppose we have 3 records in my DataBase,weither i select the first one or the second or whatever, when i click on print,i always get the first record printed and not the one selected.
Could you help me please,is it some bug or did i do something wrong?
Im using Openerp 7.0 and PRD 3.9.1
Thank you

**Comment by soukainasb** [comment]
Thank you for your answer.
Yes I put the parameter and added the filter in my datasource.
When i print or preview my report in PRD,i have a dropdown list where I choose my record,and it's displayed correctly.
But it doesn't seem to work in OpenERP,i got always the first record in the DataBase printed no matter what record i choose.

**Comment by soukainasb** [comment]
I resolved my issue.
Actually,in my case to make it work in OpenERP,i had to delete the filter.
