### ISSUE TITLE
Pentaho Reports For OpenERP - Many New Changes

### ISSUE THREAD

**Issue by richard-willdooit** [WilldooIT/Pentaho-reports-for-OpenERP#114]
Hello everyone,

Just letting you know that some exciting new features have been merged.  This includes storing report selections, a report scheduler allowing reports to run using the OpenERP scheduler and being emailed / messaged, and the ability to have functions and expressions create the default prompt values.

Check out the readme at https://github.com/WillowIT/Pentaho-reports-for-OpenERP and the wiki at https://github.com/WillowIT/Pentaho-reports-for-OpenERP/wiki/Significant-Changes.

Enjoy,

Richard

@jon-willowit @thomas-willowit @doug-willowit 
@agb80 @andhit-r @aschenkels-ictstudio @BaconConsult @bdunnaway @bretif @ccdos @claudkho @cocohard @corentinpb @cormaza @crsilveira @cssaritama @cube404 @dengwei @diassynthesis @digitalsatori @dnt83 @dw250100785 @ejzn @elnomade @enapps @filsys @flotho @focuzz @haraldnicola @haoxiaolong @HermesMacedo @hoangnd11 @ITPS @jackjc @jamesbondini @jjscarafia @jknito @JokoWaluyo123 @joshuajan @kalmenchia @kazuyahiko @kenvac @kryskool @llonchj @lxdorney @martinfpas @Martronic-SA @michalk21 @mohammedaghiourly @muerto7

**Comment by richard-willdooit** [comment]
Hello everyone,

Just letting you know that some exciting new features have been merged. This includes storing report selections, a report scheduler allowing reports to run using the OpenERP scheduler and being emailed / messaged, and the ability to have functions and expressions create the default prompt values.

Check out the readme at https://github.com/WillowIT/Pentaho-reports-for-OpenERP and the wiki at https://github.com/WillowIT/Pentaho-reports-for-OpenERP/wiki/Significant-Changes.

Enjoy,

Richard

@nadaerp @Nazarii @nick2474 @Nkburdick @openbmsjsc @OE-Tester @pentahofan @pietercvdm @pogermano @renatonlima @RickHunterEc @scleo @sexykiller @songpon @tavinshky @tejastank @theopensourcerer @turboservice @twichai @unuruu @uynil @vikingukx @yragnos

**Comment by lxdorney** [comment]
Hi Expert,

My Apologies,
I dont know if this is the right to Post my question
I have a table name "product" with the following fields: date, name,
description, price, qty, return, delivery, pullout and offtake.
I need to generate weekly report of my product:

Here is the weekly report and formula that we need to generate in pentaho
report openerp
for the periods 1-7/6/2014 is first week of the monthly
TOTAL DELIVERY = SUM OF DELIVERYs from ie. june 1 to 7

TOTAL RETURN = SUM OF RETURNs from june 1 to 7
TOTAL OFFTAKE = (BEG. WAREHOUSE + SELLING AREA) + (TOTAL DELIVERY + TOTAL
RETURN)-(END. WAREHOUSE + SELLING AREA)-TOTAL PULL-OUT

WEEKLY SALES = PRICE \* TOTAL OFFTAKE

to generate the second week need minus the TOTAL OFFTAKE of the first week
for the periods 8-14/6/2014 which is the second week of the monthly
TOTAL DELIVERY = SUM OF DELIVERYs from ie. june 1 to 7

TOTAL RETURN = SUM OF RETURNs from june 1 to 7
TOTAL OFFTAKE = (BEG. WAREHOUSE + SELLING AREA) + (TOTAL DELIVERY + TOTAL
RETURN)-(END. WAREHOUSE + SELLING AREA)-TOTAL PULL-OUT

WEEKLY SALES = PRICE \* TOTAL OFFTAKE

Can pentaho report openerp handle this?
for short the total of secondweek = totalsecondweek - totalfirstweek.

Thanks

On Thu, May 22, 2014 at 6:36 AM, Richard deMeester <notifications@github.com

**Comment by richard-willdooit** [comment]
@lxdorney Please re-submit as a new question.
