### ISSUE TITLE
Report user name parameter

### ISSUE THREAD

**Issue by aymanalazazee** [WilldooIT/Pentaho-reports-for-OpenERP#115]
I am new to this site and new to pentaho report so I hope to find answer to me question .
how to show  user name that show the report   in openerp.
i try field message with the following formula $(user_name) and $(report.user_name) and it doesn't work
and I try to pass user id  as parameter  to query like this ${user_id} but it doesn't work also.
thank you.

**Comment by kazuyahiko** [comment]
there is uid parameter u can use it

**Comment by aymanalazazee** [comment]
thank you kazuyahiko. I solve the problem by define user_id parameter in report and use it in the query
to get the username .
