### ISSUE TITLE
Debian 7 installation fails

### ISSUE THREAD

**Issue by topecz** [WilldooIT/Pentaho-reports-for-OpenERP#116]
Hi Everyone!
I have tried to install the software under three different VMs and always fails. Tried on different databases from clean ones to sales, purchase, accounting, crm, warehouse management installed, always with the same result.
The Openerp 7 doesn't shows the Settings > Actions > Pentaho Reports link while I see the System Parameters to configure it.
I can not see the container under tomcat7 either, I get the same error from the development ant launch.

I copy you the actions taken to install the software.
Thanks for your help.
Kind regards
Tomás 

Software: Openerp 7, Pentaho CE 5, Tomcat 7

*\* Checking java installation and installing those packages
aptitude install openjdk-6-jdk
aptitude install ant git ivy
*\* downloading the the Pentaho-reports-for-OpenERP
git clone https://github.com/WillowIT/Pentaho-reports-for-OpenERP.git
cd Pentaho-reports-for-OpenERP
cd java_server/
ant
ant launch ## no access to the software

cd Pentaho-reports-for-OpenERP/
cp -vfR openerp_addon /opt/openerp/v7/addons/
chown -vfR openerp:openerp /opt/openerp/v7/addons/pentaho_addon

vim /etc/openerp/openerp-server.conf
service openerp restart

aptitude install tomcat7
vim /etc/tomcat7/tomcat-users.xml
vim /etc/tomcat7/server.xml
tail /var/log/tomcat7/catalina.out

cp /root/Pentaho-reports-for-OpenERP/java_server/dist/pentaho-reports-for-openerp-7.5.1.war /var/lib/tomcat7/webapps
ls /var/lib/tomcat7/webapps
/etc/init.d/tomcat7 stop
/etc/init.d/tomcat7 start 

*\* ant launch state
     [java] INFO: Attempting to start XML-RPC server at /0.0.0.0:8090
     [java] Jun 10, 2014 5:16:20 AM com.willowit.application.StandaloneReportServer main
     [java] INFO: Started successfully
     [java] Jun 10, 2014 5:16:20 AM com.willowit.application.StandaloneReportServer main
     [java] INFO: Accepting requests
*\* Result: NO ACCESS

*\* Tomcat state: working
*\* Tomcat app under http://192.168.1.13:8081/pentaho-reports-for-openerp-7.5.1
Estado HTTP 405 - El Metodo HTTP GET no está soportado por esta URL
The HTTP GET method is not supported.

**Comment by kazuyahiko** [comment]
u need to deploy war file to java server

**Comment by topecz** [comment]
Thanks @kazuyahiko, it is already deployed with the following command and verified with the tomcat admin app:
cp /root/Pentaho-reports-for-OpenERP/java_server/dist/pentaho-reports-for-openerp-7.5.1.war /var/lib/tomcat7/webapps

**Comment by kazuyahiko** [comment]
so have u install the pentaho addons
u need instal taht so the pentaho menu will appear

**Comment by topecz** [comment]
@kazuyahiko Yes it does, I found it under Actions > Reports > selecting a report, but not under Actions > Pentaho Reports as is explained. So, after selecting a report now you can select the Pentaho reports option. SOLVED.
Still remains the war question. I have to check that everything works properly. Today's job ;)
Thanks

**Comment by kazuyahiko** [comment]
ok oh it mean u use v7 
in v7 the menu is in the action reprot

**Comment by richard-willdooit** [comment]
@topecz Although that is not the way we normally deploy the war file (we use the tomcat manager interface) there should be no reason it would fail the way you have done it.  If you have no success, though, perhaps you could try deploying it through that interface?  Let us know

**Comment by richard-willdooit** [comment]
@topecz Also, could you try deploying the pre-built war file available for download from http://cloud1.willowit.com.au/dist/pentaho-reports-for-openerp.war

**Comment by topecz** [comment]
@richard-willowit I tried all possible solutions once it failled in the first VM, done in all tree VM, compilled war, the first one, my oen complilation, through the admin manager, all possible variables. But the result was always the same.
Now it is working and it is OK for me.
