### ISSUE TITLE
[Test V8] testing pentaho report in trunk/odoo/v8

### ISSUE THREAD

**Issue by flotho** [WilldooIT/Pentaho-reports-for-OpenERP#118]
Hy,

just for your information, I open this post to inform you that I will work on trunk/odoo/v8.
All my comments will be stored in this post

**Comment by richard-willdooit** [comment]
Awesome.  I am very interested to hear if there is much to do.

**Comment by richard-willdooit** [comment]
I have created and done some alpha testing on a version80 branch.

**Comment by richard-willdooit** [comment]
Most basic functionality has been tested and is working on the new version 8.0 branch.
