### ISSUE TITLE
Passing parameters to the report

### ISSUE THREAD

**Issue by achinta** [WilldooIT/Pentaho-reports-for-OpenERP#12]
Hello,

Thanks for the excellent addon. This is not an issue, but a query. 

How can we pass parameters to the report?

Regards
Ajay

**Comment by richard-willdooit** [comment]
Hey, Ajay, sorry for the delay in getting back to you.  The latest version is greatly enhanced in this area, and there is some basic guidance regarding parameters in the OpenERP module description.

Let us know how you go.

**Comment by achinta** [comment]
Hi Richard,

Thanks for the response. I defined some parameters in the report and they are being prompted for when we launch the report using a menu in OpenERP.

But I am not sure how to use the parameters to filter the data in the reports, when the data source is OpenERP Objects. I tried to use ${parameter_name} in the Filters, but it did not help. I am using PRD 3.9.

Thanks
Ajay

**Comment by richard-willdooit** [comment]
Could you email me directly at richard@willowit.com.au and send your prpt file.  What you are saying you are doing sounds correct, using the parameter that way in the filter.
