### ISSUE TITLE
multipe value parameter

### ISSUE THREAD

**Issue by aymanalazazee** [WilldooIT/Pentaho-reports-for-OpenERP#120]
I hope to find help in my issue.I build sql query to get value from database based on multiple value parameter . for example to get all employee in one or more department so I will write the query like this
select \* from employee  e  where  e.department_id in(${parameter_dept})
it work when user select one or more department but I want the query to return all employee
in all department if user doesn't select any dept . of course I want to do that without adding 
Alldept option to query the fill the multiple value list. so the question  is how to make the multiple value parameter optional in pentaho report integrated with openerp.

**Comment by richard-willdooit** [comment]
Hi, sorry about the delay in responding.

We have generally approached this by adding a parameter to the selection for all departments (which you don't want to, I know, but for completeness in answering).

So the query to return the parameter_dept is unioned with a fixed parameter (e.g. id = 0, name='All') or (deptname = '*') or somesuch.

Then

```
select * from employee e where e.department_id in (${parameter_dept}) or ${parameter_dept} = 0
```

Can you not, though,

```
select * from emplyee e where e.department_id in (${parameter_dept}) or '${parameter_dept}' = ''
```

**Comment by richard-willdooit** [comment]
@aymanalazazee I am closing this as I have not heard back.
