### ISSUE TITLE
Pdf formate rendering 

### ISSUE THREAD

**Issue by aymanalazazee** [WilldooIT/Pentaho-reports-for-OpenERP#124]
I used pentaho report designer version 5.1 to build report contains arabic text . when render the report locally in pdf format it work . but when I transfer the report to openerp and render as pdf formate the arabic text not appear what is the problem .please help me.

**Comment by flotho** [comment]
Hy, didi you check that your arabic fonts are available on the server?
Didi you chekc the version of your libraries on the server?

regards

**Comment by aymanalazazee** [comment]
hi flotho,
the fonts are available on the server?
but I don't know where you mean by libraries.

**Comment by aymanalazazee** [comment]
the fonts are available on the server?
but I don't know where you mean by library.

**Comment by thomas-willdooit** [comment]
@aymanalazazee 

What you need to do is install the fonts on the server where you have the pentaho renderer installed. 

On Centos (and probably most Linuxes) that location is in /usr/share/fonts. You may need to restart tomcat for them to be available. 

Once complication might be that you are using the standard serif or sans-serif font in your report, in which case it may not be possible to identify the actual font getting used, so I would recommend specifying the font more directly, E.g. Time new Roman, Arial etc. Then you know exactly which font file needs to be copied to the server. You can specify the font used for the whole report by clicking on "Master Report"  in the structure tab, and then selecting the font as per usual. 

To add to flotho's advice, the library is the .war file that you would have deployed into tomcat. The latest version is available [here](http://cloud1.willowit.com.au/dist/pentaho-reports-for-openerp.war). If after copying the font files to your server you are still having issues, redeploy the war file to tomcat.
