### ISSUE TITLE
Cannot Print Excel Report With Columns More Than 256

### ISSUE THREAD

**Issue by eddytan** [WilldooIT/Pentaho-reports-for-OpenERP#126]
Hi, I need to print using Excel 2007 format as my report have more than 256 columns which is the maximum limit of Microsoft office Excel (2003) format
If I use 2003 format I'll receive this error message:

<code>org.pentaho.reporting.engine.classic.core.ReportProcessingException: Failed to process the report
    at org.pentaho.reporting.engine.classic.core.layout.output.AbstractReportProcessor.processReport(AbstractReportProcessor.java:1709)
    at org.pentaho.reporting.designer.core.actions.report.preview.PreviewExcelAction$ExportTask.run(PreviewExcelAction.java:124)
    at java.lang.Thread.run(Thread.java:679)
Caused by: java.lang.IllegalArgumentException: Invalid column index (256).  Allowable column range for BIFF8 is (0..255) or ('A'..'IV')</code>

but it works if I choose Excel 2007 from the Pentaho Designer
but the pentaho report selection from the module didn't provide the selection for Excel 2007 format

``` python
VALID_OUTPUT_TYPES = [('pdf', 'Portable Document (pdf)'),
                      ('xls', 'Excel Spreadsheet (xls)'),
                      ('csv', 'Comma Separated Values (csv)'),
                      ('rtf', 'Rich Text (rtf)'),
                      ('html', 'HyperText (html)'),
                      ('txt', 'Plain Text (txt)'),
                      ]
```

I tried to add ('xlsx', 'Excel (2007)') but it's not working, haha
what is the key value to print Excel 2007 report ?
thanks dude

**Comment by richard-willdooit** [comment]
When I get some free air, I will look in to this.  Hopefully in the next few weeks.  Sorry, but things are very busy here :(

**Comment by eddytan** [comment]
nevermind richard, 
will appreciate it most, it'll be useful for others too
thanks a lot :)

**Comment by richard-willdooit** [comment]
@edxz OK, this has now been done.

See the wiki for more details.

**Comment by richard-willdooit** [comment]
@edxz I hope this all works for you, now.
