### ISSUE TITLE
Styles not working within subreports when deployed within Odoo V8

### ISSUE THREAD

**Issue by jccastiaux** [WilldooIT/Pentaho-reports-for-OpenERP#138]
Hi,

First of all thank you very much for this plug-in that helps a lot when implementing complex reports.

I work with the Odoo V8 plugin and Pentaho Report Designer 5.1.
I use the Style Definition in order to add style rules to our report (local styles within style.xml).
Within my master report, I have a subreport.

When I run our report from the Pentaho Report Designer, styles are applied to both master and sub reports.

Now when I deploy the report within Odoo V8, the styles are applied to the elements located within the master report, but not to the elements located within the subreport.

I've tried to replace the Pentaho "jar" files within the "war" but without success.
I also tried to reference an external style file, but this file is of course not deployed when I upload the report to Odoo V8 (maybe this could be a feature for future versions of the plugin;).

Could you help me on this?

Thank you in advance,

Jean-Christophe

**Comment by richard-willdooit** [comment]
@jccastiaux I have not used style features, so am unable to say much.  At this point, @pietercvdm is looking in to a particular war build problem relating to 5.1.  May I suggest we wait for that to be resolved before we consider this further.  I must say I am surprised, as the style.xml is just included with the prpt file, is it not, so should have either worked correctly for both the main and sub reports, or neither.  As it works in the designer, but not within Odoo, the implication is along the lines of what you are suggesting - that a proper 5.1 deployment may sort the problem out.  Hopefully, we will have something there soon.

**Comment by jccastiaux** [comment]
Thank you for your answer, and I agree with your suggestion to wait until you have a working 5.1 deployment.

**Comment by flotho** [comment]
@jccastiaux , in order to integrate faster the latest 5.1 in this module, could you vote and follow this : http://jira.pentaho.com/browse/PRD-5221
Actually it seems that there is a build issue in the ivy script (https://github.com/WillowIT/Pentaho-reports-for-OpenERP/issues/121)

**Comment by jccastiaux** [comment]
It looks like the mentioned issue is closed. I'm now following it but
wasn't able to vote for it.

_Jean-Christophe Castiaux_
Line Manager

Mobile: +32 474 85 03 76
Tel: +32 2 888 31 26

_Acsone sa/nv http://www.acsone.eu_

**Comment by flotho** [comment]
The issue has been reopened, vote for it ;-)

**Comment by richard-willdooit** [comment]
@jccastiaux @flotho So I can now close this?
