### ISSUE TITLE
Launch the Ant service in background

### ISSUE THREAD

**Issue by soukainasb** [WilldooIT/Pentaho-reports-for-OpenERP#143]
I am using Windows 7 and OpenERP 7. Everytime i need to start Ant, i launch it from Windows command prompt. But since the service isn't launched in background, everytime the command prompt is closed, so is the service.how could i keep the service launched even when i close the command prompt
My knowledge on Java is really poor. please could someone help me how to solve this.
Thank you

**Comment by flotho** [comment]
Hi @soukainasb,

In order to deploy correctly your environment, I recommand you to :
1. Install an apache tomcat on a server
2. DL the .war from https://github.com/WillowIT/Pentaho-reports-for-OpenERP#quick-start
3. Deploy the war in your tomcat installation

Everything will work fine then

**Comment by richard-willdooit** [comment]
@soukainasb 

@flotho is correct - in any environment, the service will stop unless a java container is running it.  We use tomcat for all our installations.  It is a solid solution.
