### ISSUE TITLE
Please help me with an error (AttributeError(e)\nAttributeError: "Field \'behaviour\' does not exist in object )!

### ISSUE THREAD

**Issue by vikingukx** [WilldooIT/Pentaho-reports-for-OpenERP#147]
I have 2 database on the same openerp 7 (Ubuntu server 12.04 OS),
The first databse, it ran OK.
The second, it's not OK. When i exported to HTML or PDF or Excel,..., I've got an error:
OpenERP Server Error
Server Traceback (most recent call last):
  File "/opt/openerp/server/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/openerp/server/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 654, in dispatch
    res = fn(db, uid, *params)
  File "/opt/openerp/server/openerp/addons/base_report_to_printer/report_service.py", line 48, in exp_report_get
    data = report.behaviour()[report.id]
  File "/opt/openerp/server/openerp/osv/orm.py", line 486, in **getattr**
    raise AttributeError(e)
AttributeError: "Field 'behaviour' does not exist in object 'browse_record(ir.actions.report.xml, 336)'"

Client Traceback (most recent call last):
  File "/opt/openerp/server/openerp/addons/web/http.py", line 285, in dispatch
    r = method(self, **self.params)
  File "/opt/openerp/server/openerp/addons/web/controllers/main.py", line 1734, in index
    req.session._db, req.session._uid, req.session._password, report_id)
  File "/opt/openerp/server/openerp/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/openerp/server/openerp/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)
Fault: <Fault Field 'behaviour' does not exist in object 'browse_record(ir.actions.report.xml, 336)': 'Traceback (most recent call last):\n  File "/opt/openerp/server/openerp/addons/web/session.py", line 89, in send\n    return openerp.netsvc.dispatch_rpc(service_name, method, args)\n  File "/opt/openerp/server/openerp/netsvc.py", line 292, in dispatch_rpc\n    result = ExportService.getService(service_name).dispatch(method, params)\n  File "/opt/openerp/server/openerp/service/web_services.py", line 654, in dispatch\n    res = fn(db, uid, *params)\n  File "/opt/openerp/server/openerp/addons/base_report_to_printer/report_service.py", line 48, in exp_report_get\n    data = report.behaviour()[report.id]\n  File "/opt/openerp/server/openerp/osv/orm.py", line 486, in __getattr__\n    raise AttributeError(e)\nAttributeError: "Field \'behaviour\' does not exist in object \'browse_record(ir.actions.report.xml, 336)\'"\n'>

**Comment by richard-willdooit** [comment]
This error is coming from "base_report_to_printer".  This is an addon module, and it seems the error is happening before the call to Pentaho.  You may need to run an upgrade on that module for the other database, but I strongly suspect this is not a problem in this addon.

**Comment by richard-willdooit** [comment]
Have not heard back.  Closing this issue.
