### ISSUE TITLE
[8.0] Incorrect username and/or password - proxy_argument contains empty password, auth_crypt?

### ISSUE THREAD

**Issue by svenpetersen** [WilldooIT/Pentaho-reports-for-OpenERP#149]
Hello,

with the latest odoo 8.0 code from github and the now auto-installed auth_crypt module I'm getting an "Incorrect username and/or password" error, when printing an object based report. In RC01 it was fine.

The proxy_argument in execute_report contains an empty password:

{'prpt_file_content': <xmlrpclib.Binary instance at 0xb0f80bac>, 'connection_settings': {'openerp': {'login': u'admin', 'host': u'127.0.0.1', 'password': u'', 'db': u'conexus_80', 'port': u'8069'}, ...

Seems like current_user.password returns only empty strings with auth_crypt installed.

**Comment by richard-willdooit** [comment]
Will look in to this.  Ty

**Comment by richard-willdooit** [comment]
OK, I have a workaround for this that will have to wait until next week to be properly integrated.

We already have the email patch which uses duplicate users with duplicated security settings.  We will extend this to be standard in 8 for all Pentaho reporting functions, not just emailing.

In the meantime, auth_crypt can be uninstalled... although you then need to use pgadmin or somesuch to set the passwords to enable access.

**Comment by gayanj** [comment]
I have this same issue with Object based reports. I tried SQL based reports and then render just fine. But when I try Object based reports it says incorrect username and password.

**Comment by richard-willdooit** [comment]
Yes,  That is because sql based reports gather the data directly without refererence to the user who called the report, accessing postgres directly.  The object based report creates a session for the user using xmlrpc.

As I said, we have a "patch" that works which is due to be integrated and tested.  It as marked as a high priority.

Cheers.
