### ISSUE TITLE
Problems with parameter passing in query based reports

### ISSUE THREAD

**Issue by jplevy** [WilldooIT/Pentaho-reports-for-OpenERP#150]
Hello,

I've have an object based report for account.move.line and I've succeed in sending a date paremeter with  datepicker.

What I have done is:

create a parameter
Name: dateTo
Value Type: Date
Default Value Formula: =NOW()
Prompt
Display Type: DatePicker

Then I have another hidden parameter 
Name: dateToFormated
Value Type: String
Post-processing Formula: =TEXT([dateTo];"yyyy-MM-dd")
Prompt
Display Type: Text Box

and then in the Data source for the report in filters:
## field        comparator     value

date        <=                   ${dateToFormated}

And it works fine.

Then I've tried to the the same with a query based report

I've created both parameters the one from datepicker the other hidden string
and in the query I have:

SELECT aml.id, am.name as entry_name, aml.date as fecha, 
acc.code as code, acc.name as account_name, part.name as partner_name,
aml.name as linea_name, aml.debit as debit, aml.credit as credit 
FROM account_move_line as aml 
left join account_move as am on (am.id = aml.move_id)
left join account_account as acc on (acc.id = aml.account_id)
left join res_partner as part on (part.id = aml.partner_id)
WHERE  and aml.date <= ${dateToFormated}
ORDER BY am.name;

When I try to execute the report I get an error:

org.pentaho.reporting.engine.classic.core.ReportDataFactoryException: Failed at query: SELECT aml.id, am.name as entry_name, aml.date as fecha, 
acc.code as code, acc.name as account_name, part.name as partner_name,
aml.name as linea_name, aml.debit as debit, aml.credit as credit 
FROM account_move_line as aml 
left join account_move as am on (am.id = aml.move_id)
left join account_account as acc on (acc.id = aml.account_id)
left join res_partner as part on (part.id = aml.partner_id)
WHERE aml.date <= ${dateToFormated}
ORDER BY am.name;

What I'm doing wrong?
 Thanks in advance
Juan Pablo Levy

**Comment by jplevy** [comment]
Sorry, I missed to say:

prd 5.1
ubuntu 12.04
tomcat 7
Sun jdk 6
OpenERP 7

Thanks in advance
Juan Pablo Levy

**Comment by richard-willdooit** [comment]
@jplevy Firstly, I must say that I like your method of using another parameter to format the date.  It is not a mechanism I have thought of or tried.  However, I don't think it would work.

Are you saying it works for an SQL based query?  I am not sure how the integrator would treat the scenarios differently.  We pass the parameters through to the reporting engine and let the query run internally.

I am more surprised this works at all, not that it doesn't work in one scenario.

The structure is as follows:
- The Odoo integrator calls Pentaho to find out information about the parameters required.
- It does the simplest of pre-parsing on the information.  It does not use Pentaho to do this.
- First, it checks the context for a dictionary of default values (_pentaho_defaults_ is the parameter in _context_).
- Secondly, it checks for a hard coded default value within the report.
- Thirdly, it checks for default formulae - however, the only one it attempts to deal with is =NOW().
- Then the pop-up wizard is displayed, if required.
- If the wizard is displayed  and  you have installed **pentaho_report_selection_sets**, the UI can override the defaults from a saved selection sets.
- The entered values are then submitted to the report, and are not dealt with at all.  This means that to my understanding, the _Post-processing Formula_ will never be executed.  If it was, it was executed before the wizard and it will not reflect the entered values.

Can you at least confirm what is being passed to the report?  What is in the value _self.data['variables']_ in **execute_report**.  Is _dateToFormatted_ in there?  What format is it in?  I suspect you don't even need it, as _dateTo_ will be also be in there, formatted correctly for odoo (OpenERP).

**Comment by jplevy** [comment]
@richard-willowit Hello, thanks for your quick anwser.

In fact the method worked for a Object Based Data Base Access. 

Then I tried for an SQL Based Query and It didn't work.

The values of the self.data['variables'] in execute_report are:
u'dateTo':u'2014-09-29', u'dateToFomatted':u''

it is empty so it seems to be that the postprocessing formula is not working at this point

the proxy_argument['report_parameters'] also passes those variables, the dateTo with a datetime.datetime(2014,9,29,0,0) and the dateToFormatted with the empty string

but it really works.

In the case of an sql based query, i'm having troubles now with executing a simple query (from openerp) I got always the following message:

class 'xmlrpclib.Fault'
 Fault 0: 'Failed to invoke method execute in class com.willowit.reporting.PentahoRenderer: Failed at query: SELECT aml.id, am.name as entry_name, aml.date as fecha, \nacc.code as code, acc.name as account_name, part.name as partner_name,\naml.name as linea_name, aml.debit as debit, aml.credit as credit \nFROM account_move_line as aml \nleft join account_move as am on (am.id = aml.move_id)\nleft join account_account as acc on (acc.id = aml.account_id)\nleft join res_partner as part on (part.id = aml.partner_id) \nORDER BY aml.id;'
traceback object at 0x7fd4606d3bd8

and this query works well in pentaho. 

Why doesn't this simple query work?

**Comment by richard-willdooit** [comment]
@jplevy The postprocessing and default formulae logic all has to be replicated by the wizard, and we made a decision that this is beyond our scope for the moment.

The proxy_argument is built from self.data, so it should contain the same values, in the correct format for the target argument (i.e. date and string).

So, I will close this issue as you should now be able to work around it?

For the new one, could you raise a new issue, as it is a different problem.  "Failed to invoke method execute" begin by re-checking all the pentaho parameters and credentials as defined in odoo.
