### ISSUE TITLE
Error Executing Based Query Report Failed to Invoke method execute - Failed at query

### ISSUE THREAD

**Issue by jplevy** [WilldooIT/Pentaho-reports-for-OpenERP#151]
Hello,

I've done a very simple sql based report and it fails to invoke it:

The sql is fairly simple:

SELECT
     "public"."account_move_line"."id",
     "public"."account_move_line"."move_id",
     "public"."account_move_line"."date",
     "public"."account_move_line"."account_id",
     "public"."account_move_line"."partner_id",
     "public"."account_move_line"."name",
     "public"."account_move_line"."debit",
     "public"."account_move_line"."credit"
FROM
     "public"."account_move_line"

(there error appears also without the quotes and the public namespace)

When tested in Report Designer it works fine:

![screenshot from 2014-09-30 16 24 44](https://cloud.githubusercontent.com/assets/7612323/4466040/d1cffbb2-48e0-11e4-9cbf-c9b6d1874e4f.png)

but when executed from openerp I got the following error:

![screenshot from 2014-09-30 16 33 08](https://cloud.githubusercontent.com/assets/7612323/4466074/13d008b8-48e1-11e4-854e-e3a90528b9e9.png)

I'm running PRD: 5.1.0.0-752, ubuntu 12.04 Desktop, OpenERP 7, postgres 9.3.5, the latest war from willowit.

Thanks in advance, and also thanks for this wonderfull module

Juan Pablo Levy

**Comment by jplevy** [comment]
I forgot to say, it is a VMWare virtual machine running in windows

**Comment by richard-willdooit** [comment]
OK, the first thing that comes to mind with this is to check the parameters set in odoo system parameters.  For sql based reports, in particular, verify
- pentaho.postgres.host
- pentaho.postgres.port
- pentaho.postgres.login
- pentaho.postgres.password

You would have had to get all this info correct to make the report work in the designer, but please check it.  They are NOT the odoo (openerp) login details, they are the postgres database credentials.

**Comment by jplevy** [comment]
Richard,

I'm really sorry to have bothered you for such a thing, it is working fine now. You were right the problem was in the system parameters, the pentaho.postgres.password was wrong and I didn't notice it, and as it worked fine by an object based report I didn't check it.

Sorry again and many, many thanks
Juan Pablo

**Comment by richard-willdooit** [comment]
No problem.  :wink:
