### ISSUE TITLE
TransactionRollbackError: could not serialize access due to concurrent update

### ISSUE THREAD

**Issue by eddytan** [WilldooIT/Pentaho-reports-for-OpenERP#153]
Hi Willow IT,
I'm experiencing an issue in Pentaho for OpenERP 7.0

Whenever I try to print prpt report with at least one dropdown parameter, I'll get this error:

```
TransactionRollbackError: could not serialize access due to concurrent update
CONTEXT:  SQL statement "SELECT 1 FROM ONLY "public"."res_users" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"
```

I've tried installing 'willow_pentaho_email_patch', but it's still happening.

can anyone guide me to solve this issue ? thanks before

and thanks a lot for the wonderful module, I've been using it since OpenERP 6.0 and OpenERP 6.1

**Comment by richard-willdooit** [comment]
The email patch is not for parameter selection (although it IS for the error you are describing, but it sounds like it can happen in another spot than what we had addressed).  Is it happening before you select the parameters, or afterwards when it is running the actual report?  Are the parameter selections compiled using an object based query?

**Comment by eddytan** [comment]
Hi Richard,
it is happening on 7,

the error is prompted when I clicked the print button of the parameter wizard
I can preview the report with no problem using pentaho designer

I've tried to generate the dropdown value using standard search and custom function and it's prompting the same error

I've tried it in windows and ubuntu too, is it happening only to me ?

P.S:
The error appears only in report with dropdown parameter, I've got no problem for report with no dropdown parameter

**Comment by richard-willdooit** [comment]
@edxz Could you send a copy of the offending prpt file?  It seems weird that it is after selecting the parameter.

**Comment by eddytan** [comment]
@richard-willowit I've send it to your email, thanks richard :)

**Comment by eddytan** [comment]
hi @richard-willowit , I've managed to print the report with dropdown parameter by changing the isolation level, this is the code that I've added to wizard/report_prompt.py:

``` python
from psycopg2.extensions import ISOLATION_LEVEL_READ_COMMITTED

class report_prompt_class(orm.TransientModel):
    _name = 'ir.actions.report.promptwizard'

    def create(self, cr, user, vals, context=None):
        cr._cnx.set_isolation_level(ISOLATION_LEVEL_READ_COMMITTED)
        return super(report_prompt_class, self).create(cr, user, vals, context)
```

maybe this will helps someone with the same problem as mine , thanks

**Comment by richard-willdooit** [comment]
@edxz Thanks for sharing that.  Not sure how that changes or fixes things, and don't have the time to delve, but seriously, thanks for the input!

**Comment by eddytan** [comment]
@richard-willowit The code changed the isolation level of the transaction to read commited, instead of serializable which is stricter and prompting out the error
http://www.postgresql.org/docs/9.1/static/transaction-iso.html
the error is displayed on insert query (when saving the print wizard value), but I don't know why it happened, because it should only prompt the error only when multiple sessions is inserting a record into the same row on serializable isolation mode

**Comment by etsinko** [comment]
Seems that I also have the same problem. In my case I had to modify report_prompt_m2m class:

``` python
class report_prompt_m2m(orm.TransientModel):
    _name = 'ir.actions.report.multivalues.promptwizard'
    _columns = {
                'x2m_unique_id': fields.integer('2M Unique Id'),
                'entry_num': fields.integer('Entry Num'),
                'selected': fields.boolean('Selected'),
                'sel_int': fields.integer('Selection Integer'),
                'sel_str': fields.char('Selection String'),
                'sel_num': fields.float('Selection Number'),
                'name': fields.char('Selection Value'),
                }

    def create(self, cr, user, vals, context=None):
        cr._cnx.set_isolation_level(ISOLATION_LEVEL_READ_COMMITTED)
        return super(report_prompt_m2m, self).create(cr, user, vals, context)
```

**Comment by eosherbini** [comment]
Dear,

I have the same issue but when i try to use the "Report Scheduler" i have installed all your modules.

[openerp server error.txt](https://github.com/WillowIT/Pentaho-reports-for-OpenERP/files/370746/openerp.server.error.txt)

**Comment by richard-willdooit** [comment]
@eosherbini 

Are you even getting this when you are running as single user?  Firstly, try the reports with only one person using a log-in, and with no other tabs accessing openerp.  You are using version 7, and this version would hit the user file.

The error is coming during the send process.  Is it going as an email or as an internal message?  Have you installed the email patch? willow_pentaho_email_patch

**Comment by eosherbini** [comment]
Dear thank you for your replay

1- i am getting the issue when i am running as single user
2- i did try it when i am the only one logging-in
3- its going as an email
4- yes i did install the email patch
