### ISSUE TITLE
 Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer

### ISSUE THREAD

**Issue by jbtatou** [WilldooIT/Pentaho-reports-for-OpenERP#157]
hello,

I have odoo v8.

I have updated to last version this day and i have this error when i want to print invoice.

I have a clear prpt file (no fields).

The error :
SEVERE [http-nio-8080-exec-29] org.apache.xmlrpc.server.XmlRpcErrorLogger.log Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer: java.lang.Integer cannot be cast to java.lang.String
 org.apache.xmlrpc.common.XmlRpcInvocationException: Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer: java.lang.Integer cannot be cast to java.lang.String

thanks.
Jb

**Comment by gayanj** [comment]
Same error here as well.

**Comment by jbtatou** [comment]
Hi,

What about this issue?
Is there a quick solution until the final solution?
thanks.
Jb

**Comment by richard-willdooit** [comment]
@jbtatou - Could you send me the offending prpt file, please.

**Comment by jbtatou** [comment]
Hi,

Please, see the attached file.

Thanks,

Jb

De : Richard deMeester [mailto:notifications@github.com] 
Envoyé : mercredi 29 octobre 2014 06:44
À : WillowIT/Pentaho-reports-for-OpenERP
Cc : jbtatou
Objet : Re: [Pentaho-reports-for-OpenERP] Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer (#157)

@jbtatou https://github.com/jbtatou  - Could you send me the offending prpt file, please.

**Comment by jbtatou** [comment]
Hello, 
I have the same result with  the "test-pentaho-inv.prpt".
Jb

**Comment by mhamra** [comment]
I've developed several reports without any problem but when i've tried to install them, they are not working in a new server with the same error getparameterinfo org.apache.xmlrpc.common.XmlRpcInvocationException: Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer: java.lang.Integer cannot be cast to java.lang.String.

I can't find what is the difference that makes this happen. None of the reports are working.

Someone has found what is the problem?

**Comment by mhamra** [comment]
i've updated (git pull) to the new version of Odoo 8 (branch 8.0) and Pentaho (branch version80) in both environment and i have the same getparameterinfo error. Someone has found a solution?

**Comment by richard-willdooit** [comment]
Sorry, guys, will try to find some time to look, again.

@jbtatou I did not get the attachment.

@mhamra Could you also send me yours.

Send to richard@willowit.com.au

**Comment by jbtatou** [comment]
Hi all,

I just sent the file.

hello all, 

I just sent the file.

De : Richard deMeester [mailto:notifications@github.com] 
Envoyé : mercredi 5 novembre 2014 22:29
À : WillowIT/Pentaho-reports-for-OpenERP
Cc : jbtatou
Objet : Re: [Pentaho-reports-for-OpenERP] Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer (#157)

Sorry, guys, will try to find some time to look, again.

@jbtatou https://github.com/jbtatou  I did not get the attachment.

@mhamra https://github.com/mhamra  Could you also send me yours.

Send to richard@willowit.com.au mailto:richard@willowit.com.au

**Comment by mhamra** [comment]
i've sent the file

**Comment by richard-willdooit** [comment]
Thanks guys.

It appears to be broken :( for object based reports.  Can't give you a time-line, but we are looking.

cheers.

**Comment by mhamra** [comment]
So, only SQL reports are working with this version? It was working ok with a version of a couple of weeks ago. Do you think reverting to an older version will solve the problem?

I can reprogram all openerp calls to sql queries as another solution. Only one question if I take this solution, 

how should i define ids parameter in the PRPT? as type Object? I couldn't find where to look for this information.

Your help will be really appreciated.!

**Comment by richard-willdooit** [comment]
@mhamra @jbtatou - Pull the latest and try again.  Cheers.

**Comment by richard-willdooit** [comment]
@mhamra Defining the ids parameter would be the same, regardless of the report type.  Simply defining the parameter as a multi select list is all that is required, of type integer.

Two approaches can then be used when developing the report - either add the ids to your query as the last step, or have a separate query which returns the ids and then use that in the parameter.

I have been intending to do some more videos / screenshots to make this clearer.  Have you seen our youtube videos?

**Comment by mhamra** [comment]
Richard,
I really appreciate your effort, thank you very much for giving the solution so quickly.

**Comment by jbtatou** [comment]
thanks a lot.
