### ISSUE TITLE
Printing Into EXCEL 2007 (XLSX) for OpenERP 6.1

### ISSUE THREAD

**Issue by trialz92** [WilldooIT/Pentaho-reports-for-OpenERP#158]
hi willow

i cannot print the report into excel 2007 XLSX

the reason i want to print into excel 2007, because i have more than 65536 data to be printed which excel 2003 could not do it...

please help me

**Comment by trialz92** [comment]
any response? thank you

**Comment by richard-willdooit** [comment]
@trialz92 All versions updated.  It is "Untested".  Please let me know how it goes for you.

**Comment by richard-willdooit** [comment]
@trialz92 If you are not wanting to use the pre-built war file on the Willow website, then you will need to re-pull the java build and rebuild the war file.  Depends what version of Pentaho you are wanting to run on.
