### ISSUE TITLE
[Help][V8]Correct way to set parameter in query base report

### ISSUE THREAD

**Issue by flotho** [WilldooIT/Pentaho-reports-for-OpenERP#171]
Hy folks,

I'm trying to set parameters to run invoice reports. I use the parameter as below
![image1](https://cloud.githubusercontent.com/assets/1043935/4862018/a2681522-6108-11e4-869f-590dddbdb0f1.png)

Unfortunately I have this issue :
`SyntaxError: JSON.parse: unterminated string at line 2 column 1029 of the JSON data`

I'm sure I am missing something, because I've already succeed in making SQL based report working without any problem.

Any help would be appreciated.

Regards

**Comment by richard-willdooit** [comment]
@flotho Use "in" as the comparator for lists of ids... ;)

**Comment by flotho** [comment]
perfect!
Thanks
