### ISSUE TITLE
OpenERP pentaho report error : Failed at query

### ISSUE THREAD

**Issue by keyur077** [WilldooIT/Pentaho-reports-for-OpenERP#175]
I am getting an error while I try to generate a report from OpenERP.
  File "/home/target/projects/orthene/pentaho_reports/wizard/report_prompt.py", line 207, in _setup_parameters
    report_parameters = proxy.report.getParameterInfo(proxy_argument)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
Fault: < Fault 0: 'Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer: Failed at query: SELECT name FROM res_partner WHERE customer=True'>

Here is how my pentaho report design looks like: 
![partner_report](https://cloud.githubusercontent.com/assets/9676612/4994054/ebddf34a-69da-11e4-8e56-3ae41cef0b58.png)
1.It is a JDBC connection with my local postgres database connection, which is a successful connection in report designer.
2.select_partner is a SQL query that fetches all the partner names to show in parameter.
SELECT name FROM res_partner WHERE customer=True
3.PartnerQuery is a SQL query that fetches name,city,phone & email of customers
SELECT name,city,phone,email FROM res_partner WHERE customer=True AND name=${partner} // ${partner} is a parameter defined
4.partner parameter is containing drop down selection of partners when we generate a report, it includes point 2 partner_query(which lists down all the partners)
![partner_parameter](https://cloud.githubusercontent.com/assets/9676612/4994086/63ea7dfe-69db-11e4-818b-7c07531bc0c7.png)

Report is working fine in Pentaho report designed & give output like this:
![print_preview](https://cloud.githubusercontent.com/assets/9676612/4994182/7fa0f734-69dc-11e4-9c33-ca988b6575f1.png)

But it is not working in OpenERP & getting an error as described on the very top.

**Comment by richard-willdooit** [comment]
@keyur077 

Could you please try with "Validate Values" unchecked?  We have had trouble with that before.

Other than that, re check the Odoo System Parameters values for:

pentaho.postgres.host
pentaho.postgres.port
pentaho.postgres.login
pentaho.postgres.password

As an aside, can I suggest that it is possibly better practice to use the parameter with Display Name with "name" and Value with "id", Value Type "integer" and then use the id in your PartnerQuery.

**Comment by keyur077** [comment]
Thanks for your quick response richard.

Yes I tried by unchecking "Validate Values". I have also rechecked all the parameters because of them report runs fine in pentaho designer.

I have changed display name with "name",value with "id" and value type "integer"(screenshot below)
![parameter_values](https://cloud.githubusercontent.com/assets/9676612/5008728/96431086-6a85-11e4-980c-062331d92667.png)

And I have changed PartnerQuery to:
SELECT name,city,phone,email FROM res_partner WHERE customer=True AND id in (${partner})

Here I have created record of sample report:
![sample_partner_report](https://cloud.githubusercontent.com/assets/9676612/5008962/c7b86a74-6a87-11e4-82b4-e6a83287bc88.png)

So when I try to open that report, I am having following error:
![report_error](https://cloud.githubusercontent.com/assets/9676612/5009178/64320e44-6a8a-11e4-9c93-38e7966a383f.png)

Full error:
  File "/home/target/projects/orthene/pentaho_reports/wizard/report_prompt.py", line 263, in fields_view_get
    self._setup_parameters(cr, uid, context=context)
  File "/home/target/projects/orthene/pentaho_reports/wizard/report_prompt.py", line 207, in _setup_parameters
    report_parameters = proxy.report.getParameterInfo(proxy_argument)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
Fault: < Fault 0: 'Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer: Failed at query: SELECT id,name FROM res_partner WHERE customer=True'>

**Comment by richard-willdooit** [comment]
OK, send me your prpt file.

BTW, does it work without any parameters?  (i.e remove the "select_partner" query entirely, and change the main query to have a hard coded parameter value...)

**Comment by keyur077** [comment]
I have send an email with both pentaho report files on richard@willowit.com.au email. Please check & review. Thanks.

**Comment by keyur077** [comment]
Report was working fine in pentaho report designer but pentaho.postgres.password in Settings / Technical Settings / Parameters / System Parameters of OpenERP was wrong that's why it was giving me error in OpenERP.

Many thanks Richard for your efforts.

**Comment by richard-willdooit** [comment]
No problem ;)

**Comment by AbrahamOdoi** [comment]
what was the solution

**Comment by richard-willdooit** [comment]
@AbrahamOdoi 
The solution for him was that he had the wrong password configured in Settings / Technical Settings / Parameters / System Parameters.

The error referred to is quite generic, though - it basically says that something went wrong and Pentaho couldn't complete the first request.  It is almost always a configuration problem, so check all of the settings in the system parameters as per the README.
