### ISSUE TITLE
paramater field selection to many2one field

### ISSUE THREAD

**Issue by kl-adonze** [WilldooIT/Pentaho-reports-for-OpenERP#176]
Hello,

In the parametrs generated by penatho report, how to change the field selection to many2one ?
I want to use domain to filter data in th wizard.

Thanks

**Comment by richard-willdooit** [comment]
The parameters do not use domains.  They have been generically written.  The way to use the filter is to define a 2nd query in the report designer, and use that query to return ids, or whatever.

The concept is the same for SQL queries or object based queries.

Eg

```
main_query : SELECT name, email, phone FROM res_partner WHERE id=${chosen_id}

get_ids: SELECT name AS x_name, id AS x_id FROM res_partner

Parameter:
    name: chosen_id
    value type: integer
    display type: drop down (or single value list)
    query: get_ids
    value: x_id
    display name: x_name
```

Obviously, naming the columns as x_name and x_id is not necessary, but just helps it look a bit clearer.

Or for multi:

```
main_query : SELECT name, email, phone FROM res_partner WHERE id IN ${chosen_ids}

get_ids: SELECT name AS x_name, id AS x_id FROM res_partner

Parameter:
    name: chosen_ids
    value type: integer
    display type: multi value list
    query: get_ids
    value: x_id
    display name: x_name
```

 If the report is object based, and not SQL, you MAY have to try using the value type as object, not integer.

**Comment by kl-adonze** [comment]
Thank you Richard.

But my problem is that in the wizard this appraoch not work.
Example: I have two parametrs : Country and city; In the wizard if I choose country, the field city give me the cities of this country.

Best regards

**Comment by richard-willdooit** [comment]
Sorry, the wizard is entirely auto generated.  There is no current way that you can encode this.  If you have any idea how it could be made to work without specific coding, then let us know.

Your best bet is to write a custom wizard to capture the parameters, then call the report action passing the parameters in.
