### ISSUE TITLE
Cascade report problems: Empties drop-down fields

### ISSUE THREAD

**Issue by dmorenove** [WilldooIT/Pentaho-reports-for-OpenERP#177]
Hi, I've created a multiple prompt parameters report with pentaho report-designer 5.0.1. The idea is the user must select a region (redi) from a list of regions, then the user must select one State (estado) that belongs to the previous selected region and finally the user must select a municipality belonging to the previous state to generate the report. It runs perfect in the PRD tool but when I integrate it in the openerp7 via pentaho_reports addon, I just can select the region (redi) but the rest of drop-downs fields remain empties. I have installed 

JDK: 
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)

OpenERP version 7.0

Pentaho Report Designer 5.0.1-stable

Pentaho-reports-for-OpenERP-version70

![captura de pantalla de 2014-11-13 11 29 34](https://cloud.githubusercontent.com/assets/9722291/5031703/e24179c8-6b2a-11e4-92a2-a5b16e9845c4.png)

**Comment by richard-willdooit** [comment]
No, the cascading will not work.  The list of selectable values is generated at the time the wizard is screen is generated, so the 2nd and 3rd queries will already have been executed based on a "null" result for the first.  We only call the Pentaho engine twice - once to get the parameters and their possible values, and then a second time to run the report.  In the way we have structured the system, it would be too demanding to call the engine after every entry.

There is no plan to change this behaviour, I'm sorry.
