### ISSUE TITLE
TypeError: must be string or buffer, not None

### ISSUE THREAD

**Issue by pinjisi** [WilldooIT/Pentaho-reports-for-OpenERP#181]
I created a report for the Fleet Module. When I try try to run the report from odoo 8 on Windows 8  64bit I get an error message "TypeError: must be string or buffer, not None" The report has the following script and no parameters:

SELECT fv.license_plate, fv.name vehicle,  
  fvc.amount,  fvc.name, fvc.date,
  fst.name job
FROM res_company
RIGHT OUTER JOIN fleet_vehicle fv ON fv.company_id = co._id
LEFT OUTER JOIN fleet_vehicle_cost fvc ON fv.id = fvc.vehicle_id
LEFT OUTER JOIN fleet_service_type fst ON fst.id = fvc.cost_subtype_id

![fleet report error](https://cloud.githubusercontent.com/assets/8915526/5232834/bc46fd0a-7765-11e4-8d0d-8c47a2fd9acb.png)

**Comment by richard-willdooit** [comment]
The problem line appears to be when it is trying to decode the pentaho file defnition itself.  Could you include a screenshot of the report action?  Or at a minimum, try re-loading the prpt file in to the report action.  This is indicating that there is NO prpt file associated with the created action.

Oh, one thought before I press "Comment" - Ensure that the new pentaho report action has a unique local service name ("Template Name") in the action - it could be finding two report action definitions with the same service name, and not knowing which one to use.

**Comment by richard-willdooit** [comment]
As I said in the email, "Template Name" can be anything, but it MUST be unique amongst all the odoo actions.

Try putting a ipdb.set_trace in _setup_parameters in report_prompt.py, and check that the "ir.actions.report.xml" record that has been browsed is the correct record.

**Comment by pinjisi** [comment]
Thanks you very much. Like you suggested I changed the Template Name to a unique name and that seems to work. 

In the Model I always put the main table in my sql select statement. I hope that is correct

**Comment by richard-willdooit** [comment]
Yes, that is correct.  The action will be associated with that model, and if you ever want to pass in "ids" then that is the model the action will assume it needs ids for.
