### ISSUE TITLE
Concurrency Issue When Using Email Template

### ISSUE THREAD

**Issue by DBVIJ** [WilldooIT/Pentaho-reports-for-OpenERP#182]
Hi,
Thanks for your great module.

I want to share with you what works on my end to avoid Concurrency Issue When Using Email Template.
I tried to use your patch but had a bad experience when sending mass mailing with attachments (marketing campaign). The attached file were replicated for every mail sent which used a big disk space.
Therefore I tried to find another solution.
It looks like you do not need to create a new temp cursor. Just make a commit right after attachment creation with the regular cursor.

I am using version 70.

file modified : core.py

class PentahoReportOpenERPInterface(report.interface.report_int):

```
def create(self, cr, uid, ids, data, context):
    name = self.name
    report_instance = Report(name, cr, uid, ids, data, context)
    pool = pooler.get_pool(cr.dbname)
    ir_pool = pool.get('ir.actions.report.xml')
    report_xml_ids = ir_pool.search(cr, uid,
            [('report_name', '=', name[7:])], context=context)

    rendered_report, output_type = report_instance.execute()
    if report_xml_ids:
        report_xml = ir_pool.browse(cr, uid, report_xml_ids[0], context=context)
        model = context.get('active_model')
        if report_xml.attachment and model:
            #crtemp = pooler.get_db(cr.dbname).cursor() 
            # Creating new cursor to prevent TransactionRollbackError
            # when creating attachments, concurrency update have place otherwise
            self.create_attachment(cr, uid, ids, report_xml.attachment, rendered_report, output_type, model, context=context)
            cr.commit()
            # TODO: Will remodel bellow functionality as its causes a lot of bugs, it returns previous filename
            # Error in report registration

            # service_name = check_report_name(report_name)
            # if check_report_name(report_name) != self.name:
                # Changing report stored filename

                # report_xml = ir_pool.browse(crtemp, uid, report_xml_ids[0], context=context)
                # report_xml.write({'report_name': report_name})
                # change_service_name(self.name, service_name)
                # self.name = service_name

            #crtemp.commit()  # It means attachment will be created even if error occurs
            #crtemp.close()
    return rendered_report, output_type
```

I hope you find it usefull.

Best regards

**Comment by richard-willdooit** [comment]
@DBVIJ Thanks for your input.  Yes, this solution works and probably works better, and was the way we initially approached things.  The problem with solutions like this is that it breaks a design principal.

When you create a method that does something, it should be autonomous and independent and try not to interfere with outside code.  While in reality, the solution proposed works in the circumstances you need to work (and it may work in all current circumstances), there may be a legitimate but unknown reason where the cursor should not have been committed.

For example, a hypothetical piece of code may be:

```
def xxx(self, cr, uid, context=None):
    create or update some data
    render report
    check something
    if error:
         raise error
```

In the above code, the intention may be that if the error was raised, then a full rollback should occur, undoing the created / updated data.  However, the report render has committed the cursor in the meantime.

This is all in the theories of good coding practice, which are hard to implement in the real world when building on a base that may have already contravened those theories and practices we try to stick to.  So my answer is not to say you should not do what you have done, and others may find it the best way to do things, but simply to explain why it is not the best solution for integrating in the base.

Thanks again for your input and we are glad to have as much information as possible flow in to these areas!
