### ISSUE TITLE
[Tips] How to set odoo 8 so that pentaho reports will be sent instead of the default one

### ISSUE THREAD

**Issue by flotho** [WilldooIT/Pentaho-reports-for-OpenERP#184]
In the past,

Changing the service name was sufficient for sending email with pentaho.
What is the new procedure?

regards

**Comment by richard-willdooit** [comment]
We have found no problem with simply changing the email template to point to the correct service name, in version 8.

**Comment by flotho** [comment]
Yeahhh you're right, the email template was the point!
Greaaatt thanks!

**Comment by onduex** [comment]
Hi Sirs,
In odoo8 all is working fine, except email dialog box. Receivent and templates missing after charge pentaho pdf
<img width="670" alt="mail dialogbox" src="https://cloud.githubusercontent.com/assets/7617305/22399929/343cbe78-e5a8-11e6-826c-8a9d2986cd7d.PNG">

**Comment by richard-willdooit** [comment]
@onduex 

I am sorry, but I don't know how the service change would cause this to happen?  You may be stuck with debugging to work out where and how it has removed the address field.  It is an odd one, I agree.

Richard
