### ISSUE TITLE
Calling Pentaho Report

### ISSUE THREAD

**Issue by pinjisi** [WilldooIT/Pentaho-reports-for-OpenERP#186]
I know how to add Pentaho Reports to odoo 8 menus.  I want to use Pentaho all the way.  Can I call a Pentaho report from .py file (using Python code)?  Give an example please

**Comment by richard-willdooit** [comment]
If you do not provide a "linked menu item", then the action created is a standard report action, and can be called from odoo in exactly the same way as a regular report.  So, to call from an odoo button, the odoo button should be defined to call a report action, and the report action is defined exactly the same as a normal rml or qweb report, except that you specify it as a pentaho report.  As long as the report correctly deals with the passed in "ids" parameter to select it's data, then there are no real gotchas.

In fact, we frequently create invoices or quote layouts in Pentaho for our clients, and then just update the odoo standard report action to be a Pentahoo report action with the appropriate prd loaded, and it just works - for the print button, for the print pulldown, and even for emailing as an attachment.
