### ISSUE TITLE
How to run Ant service in background with script on ubuntu

### ISSUE THREAD

**Issue by kl-adonze** [WilldooIT/Pentaho-reports-for-OpenERP#187]
Hi all,

I run ant service with nohup on ubuntu but always it fall. and I must to run ant service every day.
Plz how run ant with a script like odoo.

Best regards

**Comment by thomas-willdooit** [comment]
Hello,
Generally for production machines, we recommend that you run the pentaho server in a container such as [Tomcat](http://tomcat.apache.org/). You can get a copy of the .war file from [here](http://cloud1.willowit.com.au/dist/pentaho-reports-for-openerp.war).

**Comment by kl-adonze** [comment]
Hi,

Thanks for replay.
Plz can you describe how to do run pentaho on apache.

Thanks in advance
Le 12 janv. 2015 22:13, "thomas-willowit" notifications@github.com a
écrit :

**Comment by thomas-willdooit** [comment]
Hello,
It isn't possible to run pentaho directly under Apache as you need the java server container (in this case, that is tomcat). What you can do is have Apache act as a reverse proxy for tomcat.

The details of how to do this are beyond the scope of this project however, and there is great documentation out there, so best of luck.
