### ISSUE TITLE
Issue Regarding Pentaho Report installation for ODOO 8.0

### ISSUE THREAD

**Issue by cdasadiya** [WilldooIT/Pentaho-reports-for-OpenERP#188]
Hello ALL,

I am getting Stuck With the installation on the Pentaho Report for Odoo 8.0 in my Ubuntu system and  Where can  I find the different Library which is depended the pentaho report resigner and its related stuff.I had checked and use the so many website and web blog reference for that installation but I had not find the dependence library.

http://pvandermpentaho.blogspot.com.au/2012/05/adding-openerp-datasource-to-pentaho.html

I am also attach this image with this post

therefore   I can't create the .war file for deploying the into the tomcat7 server for run the pentaho report designer tool.

I had downloaded your  source from the below link

https://github.com/WillowIT/Pentaho-reports-for-OpenERP

And also if you find any other reference stuff or website reference link  regarding the installation than send it to me.
please help me for resolve that issue.

My Attachment Image 
![missing required packages](https://cloud.githubusercontent.com/assets/7426056/5870049/71c6f0ea-a2ea-11e4-8346-671b98d75ddf.png)

**Comment by richard-willdooit** [comment]
If you are running Pentaho version 5 or above, you do not need the OpenERP datasource to be added - it is now included by default.  If you really must use version 3.9, then let me know, but otherwise, there should be enough information in the current https://github.com/WillowIT/Pentaho-reports-for-OpenERP

Easiest is to use the pre-built war file that is linked to in the Quick Start section.  Then you don't need to worry about setting up the dependencies.

**Comment by cdasadiya** [comment]
Thanks richard-willowit ...!!
and also I am getting the same error
which was  the simillier issue i am facing now  Like 
https://github.com/WillowIT/Pentaho-reports-for-OpenERP/issues/189

**Comment by richard-willdooit** [comment]
@cdasadiya74 As I said there, why not use the pre-built war file that we link to - it has all the dependencies.

**Comment by swtlinor** [comment]
Where can one get the pre- built War file Am really confused here as am still stocked.                                                                                                                                                                                                                                                                           Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                                         From: Richard deMeesterSent: Wednesday, 4 February 2015 2:34 AMTo: WillowIT/Pentaho-reports-for-OpenERPReply To: WillowIT/Pentaho-reports-for-OpenERPSubject: Re: [Pentaho-reports-for-OpenERP] Issue Regarding Pentaho Report installation for ODOO 8.0 (#188)@cdasadiya74 As I said there, why not use the pre-built war file that we link to - it has all the dependencies.

—Reply to this email directly or view it on GitHub.

**Comment by m3gadroider93** [comment]
http://cloud1.willowit.com.au/dist/pentaho-reports-for-openerp.war

Above is the link for the pre-built .war file. It was present in the Quick Start section of the WillowIT github repo hidden as a link inside the word "here" which was hyperlinked. But anyway the link has been provided above for convenience.

All you need to do now is put the .war file in the webapps folder under tomcat and start the tomcat server. The sever should automatically deploy the webapp. Then download the Pentaho Report Willow IT module from the github repo and install in your Odoo installation.

Then change the report type to Pentaho for whatever report you want generated. Upload the design of your report and Print the report.

**Comment by swtlinor** [comment]
Thank you so much for your reply, my ODOO version is 7, is it same thing?                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                                         From: m3gadroiderSent: Wednesday, 4 February 2015 6:47 AMTo: WillowIT/Pentaho-reports-for-OpenERPReply To: WillowIT/Pentaho-reports-for-OpenERPCc: swtlinorSubject: Re: [Pentaho-reports-for-OpenERP] Issue Regarding Pentaho Report installation for ODOO 8.0 (#188)http://cloud1.willowit.com.au/dist/pentaho-reports-for-openerp.war

Above is the link for the pre-built .war file. It was present in the Quick Start section of the WillowIT github repo hidden as a link inside the word "here" which was hyperlinked. But anyway the link has been provided above for convenience.

All you need to do now is put the .war file in the webapps folder under tomcat and start the tomcat server. The sever should automatically deploy the webapp. Then download the Pentaho Report Willow IT module from the github repo and install in your Odoo installation.

Then change the report type to Pentaho for whatever report you want generated. Upload the design of your report and Print the report.

—Reply to this email directly or view it on GitHub.

**Comment by richard-willdooit** [comment]
The pre-built war file will work with version 7 too.

**Comment by cdasadiya** [comment]
Thanks All

**Comment by swtlinor** [comment]
Please, how do I or where do I go to change my report type to pentaho
because I still can not find the pentaho menu under settings/Actions please
help!!

Regards.

 Best Regards.

_Helen Omarari Alabi_
Senior Software Developer
_,_
Department of Information Systems
American University of Nigeria Yola
Mobile : +2348059946365
VOIP : 1080

**Comment by richard-willdooit** [comment]
@swtlinor In version 8, there is no Pentaho Menu.  The standard report action now has a report type which you set to Pentaho (Actions > Reports > Report Type)
