### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by swtlinor** [WilldooIT/Pentaho-reports-for-OpenERP#189]
Hello,
Please can anyone help?? am trying to install the pentaho report for openerp7 and am getting this error when I run the "sudo ant war" on my terminal
NOTE PLS: am following this document on the net http://www.baconconsult.eu/home/our-products/openerp/openerp-printing/reporting---pentaho-and-openerp/pentaho-java-report-server and am on the 6th step when i accountered this error.

BUILD FAILED
/home/helen/Pentaho-reports-for-OpenERP-version70_pentaho39/java_server/build.xml:27: impossible to resolve dependencies:
    resolve failed - see output for details

**Comment by juaniyyo** [comment]
Hi,

You've installing dependecies. Tray download IVY whit dependencies.

**Comment by richard-willdooit** [comment]
As @juaniyyo said, check the dependencies, but save yourself the headaches and use the pre-built war file.
