### ISSUE TITLE
[8.0]Installing with latest release failed

### ISSUE THREAD

**Issue by flotho** [WilldooIT/Pentaho-reports-for-OpenERP#190]
Hy,

I'm trying to install your module with and I have this error :

```
File "/opt/odoo/additional_repos/pentaho-for-openerp/openerp_addon/pentaho_reports/ui.py", line 23, in __init__
    if not('pentaho','Pentaho Report') in self._columns['report_type'].selection:
KeyError: 'report_type'
```

It failed everytime with or without english language, with or without demo datas.
Any help would be appreciated

**Comment by iceship** [comment]
Hi,
I've got the same problem.

custom\addons\pentaho_reports\ui.py", line 23, in **init**
    if not('pentaho','Pentaho Report') in self._columns['report_type'].selection:
KeyError: 'report_type'

**Comment by juaniyyo** [comment]
Hi,
I've got the same problem and fix it installing trunk branch of pentaho-report.

**Comment by richard-willdooit** [comment]
OK, this has me a little stumped, and I can't reproduce it.  The class in question inherits from base, and the module is dependent on base, and the column is (or should be) defined in base/ir/ir_actions.py

Could you please insert an:

```
ipdb
ipdb.set_trace()
```

at line 23 in pentaho_reports/ui.py and type

```
pp self._columns
```

The crash could be averted by using self._columns.get('report_type',[]).selection, but in fact, would indicate that something else is a bit screwy - it should be defined at this point.

**Comment by richard-willdooit** [comment]
I have tested with a code base from odoo which is about 2 weeks old, and the latest from this repository.  Any light appreciated, as I am having no problems.  Steps: create new database, and install Pentaho Reports.

Are you able to just do those two steps in that sequence or not?

**Comment by richard-willdooit** [comment]
Fix coming.  It is in regards to an api change.  Will attempt to re-do tomorrow.  I will try to ensure it is backward compatible with the old-api.  Stay tuned.

**Comment by flotho** [comment]
Hy I tried your proposal

```
self._columns.get('report_type',[]).selection, 
```

At line 23 without any success.

**Comment by flotho** [comment]
I tried with the odoo commit d4027e6 and it seems to work but not with the latest release
