### ISSUE TITLE
Is it normal that there is no more email_patch in the 8.0 branch?

### ISSUE THREAD

**Issue by flotho** [WilldooIT/Pentaho-reports-for-OpenERP#191]
Hy,
Somebody could explain me if it's normal?
regards

**Comment by richard-willdooit** [comment]
Correct.  Because of the forced password encryption, and because of the changed handling of sign-in tokens for emailed reports, the need to create a duplicate user for reporting became more necessary, and it now does so in all reporting cases, not just when emailing.
