### ISSUE TITLE
odoo report error

### ISSUE THREAD

**Issue by Toni1974** [WilldooIT/Pentaho-reports-for-OpenERP#197]
Hi, I created a simple report (código article and description), runs from Pentaho without problems, but from odoo y take the next error:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20150306\server.\openerp\http.py", line 530, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20150306\server.\openerp\http.py", line 567, in dispatch
  File "C:\Program Files (x86)\Odoo 8.0-20150306\server.\openerp\http.py", line 303, in _call_function
  File "C:\Program Files (x86)\Odoo 8.0-20150306\server.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150306\server.\openerp\http.py", line 300, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20150306\server.\openerp\http.py", line 796, in __call__
  File "C:\Program Files (x86)\Odoo 8.0-20150306\server.\openerp\http.py", line 396, in response_wrap
  File "C:\Program Files (x86)\Odoo 8.0-20150306\server\openerp\addons\web\controllers\main.py", line 949, in call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20150306\server\openerp\addons\web\controllers\main.py", line 941, in _call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20150306\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150306\server\openerp\addons\pentaho_reports\wizard\report_prompt.py", line 361, in fields_view_get
  File "C:\Program Files (x86)\Odoo 8.0-20150306\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150306\server\openerp\addons\pentaho_reports\wizard\report_prompt.py", line 199, in _setup_parameters
  File "xmlrpclib.pyc", line 1224, in __call__
  File "xmlrpclib.pyc", line 1578, in __request
  File "xmlrpclib.pyc", line 1264, in request
  File "xmlrpclib.pyc", line 1297, in single_request
  File "xmlrpclib.pyc", line 1473, in parse_response
  File "xmlrpclib.pyc", line 793, in close
Fault: <Fault 0: 'Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer: Unable to parse the document: ResourceKey{schema=org.pentaho.reporting.libraries.docbundle.bundleloader.ZipResourceBundleLoader, identifier=content.xml, factoryParameters={org.pentaho.reporting.libraries.resourceloader.FactoryParameterKey{name=repository}=org.pentaho.reporting.libraries.repository.zipreader.ZipReadRepository@44888d8d, org.pentaho.reporting.libraries.resourceloader.FactoryParameterKey{name=repository-loader}=org.pentaho.reporting.libraries.docbundle.bundleloader.ZipResourceBundleLoader@2b147f97}, parent=ResourceKey{schema=org.pentaho.reporting.libraries.resourceloader.loader.raw.RawResourceLoader, identifier=[B@272a2609, factoryParameters={}, parent=null}}'>

I have the verification them Parameters (pentaho.postgres.host, pentaho.postgres.password, etc ...) but without result.
My installation: Windows 8.1, odoo 8, pentaho designer 5.3.

Can you help me please?

Thanks.

**Comment by richard-willdooit** [comment]
@Toni1974  Does the report run without any parameters defined?  Do you have the system configuration parameters set correctly inside Odoo?
(If it is object based, recheck pentaho.openerp.xml.interface and pentaho.openerp.xml.port
If it is sql based, recheck pentaho.postgres.host pentaho.postgres.port pentaho.postgres.login pentaho.postgres.password)

Please read the README for information about these parameters

**Comment by Toni1974** [comment]
Good morning, thanks for reply.
Yes, all the parameters are ok, there is no parameters defined. Is a simple sql based report with two fields.

Enviat des de Samsung MobileRichard deMeester notifications@github.com ha escrit:@Toni1974 Does the report run without any parameters defined?  Do you have the system configuration parameters set correctly inside Odoo?
(If it is object based, recheck pentaho.openerp.xml.interface and pentaho.openerp.xml.port
If it is sql based, recheck pentaho.postgres.host pentaho.postgres.port pentaho.postgres.login pentaho.postgres.password)

Please read the README for information about these parameters

**Comment by Toni1974** [comment]
Hi, here you are the print screen:

I create a role (openerp, openerp) in Postgresql and I test it successfull.

Regards.

De: Richard deMeester [mailto:notifications@github.com] 
Enviado el: jueves, 19 de marzo de 2015 23:41
Para: WillowIT/Pentaho-reports-for-OpenERP
CC: Toni1974
Asunto: Re: [Pentaho-reports-for-OpenERP] odoo report error (#197)

@Toni1974 https://github.com/Toni1974  Does the report run without any parameters defined? Do you have the system configuration parameters set correctly inside Odoo?
(If it is object based, recheck pentaho.openerp.xml.interface and pentaho.openerp.xml.port
If it is sql based, recheck pentaho.postgres.host pentaho.postgres.port pentaho.postgres.login pentaho.postgres.password)

Please read the README for information about these parameters

**Comment by Toni1974** [comment]
Hi Richard, if I try another report, invoice report for example, i get another error like this: <class 'xmlrpclib.Fault'>,,<traceback object at 0x06465AF8>
Regards.

**Comment by Toni1974** [comment]
sorry, here are the error:
class 'xmlrpclib.Fault',,traceback object at 0x06465AF8

**Comment by richard-willowit** [comment]
Yes, again, it is indicating a parameter issue to me.  Can you show me all the system configuration parameters you have defined in Odoo?

**Comment by richard-willdooit** [comment]
@Toni1974 Yes, again, it is indicating a parameter issue to me.  Can you show me all the system configuration parameters you have defined in Odoo?

**Comment by Toni1974** [comment]
Hi, here are the parameters (I try with others too):
pentaho.postgres.host localhost
pentaho.postgres.port 5432
pentaho.postgres.login odoo
pentaho.postgres.password odoo

the same configuration in kubuntu Works perfectly, a report SQL based with one field.

Regards.

**Comment by Toni1974** [comment]
Here is the print screen:

De: Richard deMeester [mailto:notifications@github.com] 
Enviado el: domingo, 22 de marzo de 2015 23:14
Para: WillowIT/Pentaho-reports-for-OpenERP
CC: Toni1974
Asunto: Re: [Pentaho-reports-for-OpenERP] odoo report error (#197)

@Toni1974 https://github.com/Toni1974  Yes, again, it is indicating a parameter issue to me. Can you show me all the system configuration parameters you have defined in Odoo?

**Comment by Toni1974** [comment]
Hi, I think I found the problem, I think it is the version of report designer, a report created with 5.0.1 gives no problems, but the same report with 5.3.0.0 if it gives the above error.
Regards

**Comment by richard-willdooit** [comment]
Ahh, we have not upgraded our engine and dependencies for 5.3!  Aaargh.  Too much to do!!!  Will try and get around to this soon.  Thanks for reporting your issue...

**Comment by Toni1974** [comment]
Thank you for answering!

Enviat des de Samsung MobileRichard deMeester notifications@github.com ha escrit:Ahh, we have not upgraded our engine and dependencies for 5.3!  Aaargh. Too much to do!!! Will try and get around to this soon. Thanks for reporting your issue...

**Comment by richard-willdooit** [comment]
@Toni1974 Updated.  The war file and build are all up to date, now.

**Comment by Toni1974** [comment]
Thanks a lot!!

Enviat des de Samsung MobileRichard deMeester notifications@github.com ha escrit:@Toni1974 Updated. The war file and build are all up to date, now.
