### ISSUE TITLE
OpenERP pentaho report error

### ISSUE THREAD

**Issue by abiniyam** [WilldooIT/Pentaho-reports-for-OpenERP#201]
Hello i am getting an error when i try to generate the report from odoo v8.i see some suggestion here but i doesn't work my report is simple it generates only lists of patients using odoo objects.the report is working fine in pentaho report designer.I appreciate your help in advance.
![report designer](https://cloud.githubusercontent.com/assets/9266612/6823534/24be0ce4-d2fa-11e4-9099-a11c6da2288c.JPG)
![odoo error](https://cloud.githubusercontent.com/assets/9266612/6823552/737729c4-d2fa-11e4-9ced-36774a1aa02a.JPG)

**Comment by richard-willdooit** [comment]
First, check and recheck your parameters at Settings / Technical Settings / Parameters / System Parameters
Second, check the version of the report designer - if created in version 5.3 of the designer, try an older version as the reporting engine has not been upgraded to the latest, yet.
Third, are you using the latest version of code from here?
Can you get one to work with a base model, like res.partner?

**Comment by abiniyam** [comment]
Thanks for the answer.yes i am using the latest version.The sample report i download from your website is working fine may be the problem is with designer i will try it with the older version.which versions are compatible?

**Comment by abiniyam** [comment]
Thanks it works with older version.
