### ISSUE TITLE
Proper use of "ids" for subreport

### ISSUE THREAD

**Issue by aitorbouzas** [WilldooIT/Pentaho-reports-for-OpenERP#204]
Hello,

I was trying to make an invoice report with a subreport with the taxes included in the invoice... But the subreport shows every tax that has been applied to every invoice in Odoo's database.

What am I doing wrong? Should I use "ids" parameter in other way? I'm sending the .prpt file to richard's mail.

Thank you very much,

**Comment by aitorbouzas** [comment]
I guess I need to use the "ids" parameter to filter the invoices in the parent report, and then, in the subreport import the invoice id from parent as a parameter in order to make a filter with it (in the query...) But I don't know how to do it!

**Comment by flotho** [comment]
Hy,

Here is a issue that could be reluctant : http://jira.pentaho.com/browse/PRD-5401

**Comment by aitorbouzas** [comment]
Hi @flotho,

I just resolved this issue a couple of days ago and forgot to bring the solution here. Here it is:
1. As I said, I also have two datasources, the first one contains an "ids" parameter corresponding to the id of the received objects, let's say that "ids" corresponds to the "invoice_ids". Parameter should be as: 
   Name: ids
   Label: ids
   Value Type: integer
   Display Type: Multi Value List
   Query: (the one with the ids)
   Value: invoice_id
   Display Name: invoice_id

That should filter nice. Then...
1. In the second datasource from the new subreport (the one containing the tax lines), it is a query to the invoice but only searching for tax lines fields (tax_line.name, tax_line.base and tax_line.amount). If in the Query Editor we go to Filters we should see two lines, "account.invoice" and "account.invoice.tax_line". If this is correct, continue.
2. We must create a new import parameter, and import "invoice_id" from parent to a simple name inside this subreport, like "fatherinvoice" (I just needed to avoid "_" "-" " " characters...).
3. Let's go back to filters and now click on "account.invoice". We now should add a new filter to it with:
   Field: (field corresponding to the id of the object)
   Comparator: =
   Value: ${fatherinvoice}

That did it for me! Hope it helps, if you need the example file just comment this asking for it ;)

**Comment by onduex** [comment]
Hi Softdil,
Please could you send the example file... I'm iunable to configure
:-(
tomas.pascual@onduex.com

Thanks,
