### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by aitorbouzas** [WilldooIT/Pentaho-reports-for-OpenERP#205]
How should I config the report and the OpenERP pentaho app to show especial characters like á, ñ...?

I watch them well in the preview from the Report Designer, but when I print it through the OpenERP the special characters are just deleted...

Thanks in advice

**Comment by flotho** [comment]
Hy,
Yhis mainly look like a localisation of your server hosting pentaho report server
Check that the server locale is the same as yours. Restart pentaho service to be sure that the correct locale is used by java.
Then everything should be Ok

**Comment by aitorbouzas** [comment]
Thanks for the response @floto but the server hosting the Pentaho Report Server (it's the same as the one that hosts Odoo) has the server locale configurated correctly (es_ES.UTF-8)...
Could it be that I am creating the reports from other PC? Maybe it has something to do...

**Comment by flotho** [comment]
@Softdil, to be sure, try to set locally your locale so that it's exactly the same as the server's one.

regards

**Comment by aitorbouzas** [comment]
@flotho nothing to do, I don't know what is happening with special characters...

**Comment by richard-willdooit** [comment]
I think this is all related to #183 conversation?  If not, re-open this, but it is probably better to consolidate these.

**Comment by aitorbouzas** [comment]
Just found that in HTML the report special characters are printing well... Can someone give some light about where should I look at?

Thanks
