### ISSUE TITLE
The report crashes when I set a Byte[] field

### ISSUE THREAD

**Issue by disna-sistemas** [WilldooIT/Pentaho-reports-for-OpenERP#211]
I have a report linked to account.invoice model.  The report works fine until I add (for instance) the company logo field, then I get this traceback:

![image](https://cloud.githubusercontent.com/assets/9465204/7468564/7ed43912-f30a-11e4-90cc-123e8c743dc6.png)

Is this a serialization issue?  How can I fix it?

Thanks in advance

**Comment by disna-sistemas** [comment]
Sorry, it was my fault.  The Byte[] field cannot be put directly.  I put it into a image-field and works perfect.

Regards

**Comment by flotho** [comment]
No problem, could you please close your comment if it's OK.

regards
