### ISSUE TITLE
output report name

### ISSUE THREAD

**Issue by putraadhi** [WilldooIT/Pentaho-reports-for-OpenERP#212]
Hi, Willowit Developer

I have installed module "pentaho_report" in odoo. I want to change the default output file name so that the output file name is same as purchase order name. In example, I open purchase order PO0001, I want to save it to "PO0001,pdf" automatically, but the output file name is "PO Report.pdf" (same as the report name in Settings -> Reports -> Reports). What should I do to fix this? I hope you can help me.

Regards,
Putra Adhi Anggara

**Comment by flotho** [comment]
Hy @putraadhi ,

This is mainly an Odoo issue declared on many community :
- https://www.odoo.com/fr_FR/forum/help-1/question/invoice-number-into-the-pdf-file-name-5089
- https://www.linkedin.com/grp/post/165657-5806783884192423938
- https://www.odoo.com/fr_FR/forum/help-1/question/download-file-name-change-34977

Additionally, once you print the report in the attached, the file is stored with the correct name.

regards

**Comment by putraadhi** [comment]
Hi @flotho ,

Thank you for your solution. But this solutions are used for RML file. My problem is in Pentaho Report file. Are you have solution for pentaho report file name?

Regards

**Comment by richard-willdooit** [comment]
@putraadhi 

@flotho is correct.  This is not at all a Pentaho Report concern.  It returns a generated report to the Odoo request, which then determines how to return the report to the client.  By setting a report name against the action, (at least in version 8 where refactoring ensured that no matter what the report source, the action dealt with it correctly), it should be re-naming correctly.

His links point to version 7 solutions, where the refactoring meant it worked differently for different report types.  In version 8, Save as Attachment Prefix can be used to specify a name - although by default it is limited.  We had a mod in version 7 that has not been ported to version 8 which allowed that to pick up invoice or partner details in the name.  I believe there may be some modules out there which do the renaming more cleverly, and they will work regardless of the report source.

The emailing functionality - Settings > Technical > Email > Templates - allows a report attachment (like invoices) to receive a more meaningful name, like

Invoice_${(object.number or '').replace('/','_')}_${object.state == 'draft' and 'draft' or ''}
