### ISSUE TITLE
Pentaho report integration issue in Openerp 7

### ISSUE THREAD

**Issue by jinalpatel-it** [WilldooIT/Pentaho-reports-for-OpenERP#216]
Hello 
I am getting an error while I try to generate a report from OpenERP 7
I have checked solutions of http://stackoverflow.com/questions/26862089/openerp-pentaho-report-error-failed-at-query .
But its not working for me.

My error trace is:

![github](https://cloud.githubusercontent.com/assets/9860722/8826062/6f2ba99e-30a1-11e5-8d08-b17695f9490f.png)

Can anyone help?

**Comment by richard-willdooit** [comment]
@jinalpatel-it 

OK, firstly, the prpt file you sent me works no problem.

Can you send the errors from catalina.out log file (from tomcat).  This is usually a lot more helpful for errors like this.

As you are running this on OpenERP 7 - it does not support reports from report designer 5.4.  From memory, it is only supporting reports from designer 5.1.  Please ensure this is not the problem.

Richard

**Comment by richard-willdooit** [comment]
Have not heard back - closing issue.
