### ISSUE TITLE
Object Reports with Encrypted Passwords - Input sought!!!

### ISSUE THREAD

**Issue by richard-willdooit** [WilldooIT/Pentaho-reports-for-OpenERP#219]
Dear community,

I ask for input in how we can deal with the following situation:

When Pentaho runs an object based report, it does so by creating its own isolated transaction, using the current user's credentials.

It needs to use the current user so that:
A) it respects the current user's security;
B) it correctly uses any other attributes from the current user.

To create it's own isolated transaction, the Pentaho report session needs to log in.  To log in, it needs to know the user and the user's password.

Everything is fine if the auth_crypt module is turned off.  This module is, in fact, turned on by default for Odoo version 8 (and up).  It can be uninstalled, but it would be good to have a solution around this.

Options which are considered unacceptable:
- Passing something through to the login to by-pass authentication - major security hole - definitely unacceptable.
- Setting the password temporarily on the login to a known value and using that to log in - if the report should somehow crash, the user would be locked out.

One option, which I may explore first, after we have had some comments from users perhaps,
- Set a temporary alternate password somewhere (probably not in the user record, but maybe in the config file) - perhaps timestamp it for validity time length - validate the login against this alternate temporary, random password, and remove it after the report has run.  This would have to be done in a separate cursor, cursor closed and committed, so the Pentaho session would see the values when it runs...

Any other input.

(See issue #218)

**Comment by richard-willdooit** [comment]
@doug-willowit @pietercvdm @flotho @etsinko @dnt83 @eqms @juaniyyo @DBVIJ @edxz

Hello Pentho users,

Input is sought on this issue.

**Comment by etsinko** [comment]
Hello Richard,
thanks for the fix! Are you planning to release it for v7.0 as well?

Egor

**Comment by richard-willdooit** [comment]
@etsinko 

Unfortunately, at the moment, demands on my time are such that I don't anticipate being able to look at back porting for a while.
