### ISSUE TITLE
Error odoo report

### ISSUE THREAD

**Issue by Toni1974** [WilldooIT/Pentaho-reports-for-OpenERP#220]
Hello again, I have created a new report with the v.5.01 version, 5.3 and 5.4 (from prd works fine), but when I run from odoo v.8 (debian server) gives me the error class 'xmlrpclib.Fault'. However, if I run a report created from another server, it runs normally. Any idea what could be happening? I have reviewed the installation several times and find nothing special ... Greetings.

**Comment by richard-willdooit** [comment]
@Toni1974 
- Is it an object or sql based report?
- Are there any parameters in the report?
- Can you check / send the odoo log file? Have you had a look at the catalina.out log file from Tomcat?
- Is the report that you have created on another server the same type of report (i.e. object or sql)? Does it use the same objects or tables?
- How recent is the deployment of the war file you used?  Could it be worth downloading the latest version from the Willow website and re-deploy this under Tomcat?  It is Pentaho 5.4.  Have you tried using the server running in test mode not using Tomcat?

**Comment by Toni1974** [comment]
Hi Richard, it’s a sql based report and no parameters.

I tried it with the war and the old module openerp and I had no problems, however, if I download the war and now OpenERP module and install it when I get the error

Greetings.

De: Richard deMeester [mailto:notifications@github.com] 
Enviado el: lunes, 17 de agosto de 2015 1:11
Para: WillowIT/Pentaho-reports-for-OpenERP Pentaho-reports-for-OpenERP@noreply.github.com
CC: Toni1974 toni@boirasoft.cat
Asunto: Re: [Pentaho-reports-for-OpenERP] Error odoo report (#220)

@Toni1974 https://github.com/Toni1974  
-   Is it an object or sql based report?
-   Are there any parameters in the report?
-   Can you check / send the odoo log file? Have you had a look at the catalina.out log file from Tomcat?
-   Is the report that you have created on another server the same type of report (i.e. object or sql)? Does it use the same objects or tables?
-   How recent is the deployment of the war file you used? Could it be worth downloading the latest version from the Willow website and re-deploy this under Tomcat? It is Pentaho 5.4. Have you tried using the server running in test mode not using Tomcat?

**Comment by richard-willdooit** [comment]
@Toni1974 

The fact that you say a report created on another server works fine really intrigues me.  Can you tell me if there are any errors being reported by tomcat in catalina.out?

**Comment by Toni1974** [comment]
I format the server forgive but I did what I said in the previous post, installing everything like in the old server. thanks for answering. Regards.

De: Richard deMeester [mailto:notifications@github.com] 
Enviado el: martes, 15 de septiembre de 2015 1:28
Para: WillowIT/Pentaho-reports-for-OpenERP Pentaho-reports-for-OpenERP@noreply.github.com
CC: Toni1974 toni@boirasoft.cat
Asunto: Re: [Pentaho-reports-for-OpenERP] Error odoo report (#220)

@Toni1974 https://github.com/Toni1974  

The fact that you say a report created on another server works fine really intrigues me. Can you tell me if there are any errors being reported by tomcat in catalina.out?
