### ISSUE TITLE
Error : complie war file 

### ISSUE THREAD

**Issue by alimanager** [WilldooIT/Pentaho-reports-for-OpenERP#221]
Hi, 
After 4 days of struggling to start reporting in odoo with pentaho, i still blocked in compilation of war file and the tomcat didn't work with me, it install correctly and i add the manager login. 
and this the war error : 
Buildfile: /opt/pentaho_report/Pentaho-reports-for-OpenERP-version70/java_server/build.xml

init:

compile.pre:

compile.compile:
    [javac] /opt/pentaho_report/Pentaho-reports-for-OpenERP-version70/java_server/build-res/subfloor.xml:1160: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 4 source files to /opt/pentaho_report/Pentaho-reports-for-OpenERP-version70/java_server/bin/classes
    [javac] warning: [path] bad path element "/usr/share/java/../bin": no such file or directory
    [javac] warning: [path] bad path element "/usr/share/java/servlet-api-2.5.jar": no such file or directory
    [javac] warning: [path] bad path element "/usr/share/java/jsp-api-2.1.jar": no such file or directory
    [javac] warning: [path] bad path element "/usr/share/java/el-api-2.1.jar": no such file or directory
    [javac] warning: [path] bad path element "/usr/share/java/xalan.jar": no such file or directory
    [javac] /opt/pentaho_report/Pentaho-reports-for-OpenERP-version70/java_server/src/com/willowit/application/PentahoResourceManager.java:6: package org.apache.commons.logging does not exist
    [javac] import org.apache.commons.logging.Log;
    [javac]                                  ^
    [javac] /opt/pentaho_report/Pentaho-reports-for-OpenERP-version70/java_server/src/com/willowit/application/PentahoResourceManager.java:7: package org.apache.commons.logging does not exist
    [javac] import org.apache.commons.logging.LogFactory;
    [javac]                                  ^
    [javac] /opt/pentaho_report/Pentaho-reports-for-OpenERP-version70/java_server/src/com/willowit/application/PentahoResourceManager.java:9: package org.apache.commons.lang3.exception does not exist
    [javac] import org.apache.commons.lang3.exception.ExceptionUtils;
    [javac]                                          ^
    [javac] /opt/pentaho_report/Pentaho-reports-for-OpenERP-version70/java_server/src/com/willowit/application/PentahoResourceManager.java:14: cannot find symbol
    [javac] symbol  : class Log
    [javac] location: class com.willowit.application.PentahoResourceManager
    [javac]     private static Log logger = LogFactory.getLog(PentahoResourceManager.class);
    [javac]                    ^
    [javac] /opt/pentaho_report/Pentaho-reports-for-OpenERP-version70/java_server/src/com/willowit/application/StandaloneReportServer.java:3: package org.apache.xmlrpc.server does not exist
    [javac] import org.apache.xmlrpc.server.XmlRpcServer;
    [javac]                                ^
    [javac] /opt/pentaho_report/Pentaho-reports-for-OpenERP-version70/java_server/src/com/willowit/application/StandaloneReportServer.java:4: package org.apache.xmlrpc.server does not exist
    [javac] import org.apache.xmlrpc.server.PropertyHandlerMapping;
    [javac]                                ^
    [javac] /opt/pentaho_report/Pentaho-reports-for-OpenERP-version70/java_server/src/com/willowit/application/StandaloneReportServer.java:5: package org.apache.xmlrpc.webserver does not exist
    [javac] import org.apache.xmlrpc.webserver.WebServer;

**Comment by alimanager** [comment]
Help , Help , by the way i follow this 2 tuto : http://www.schenkels.nl/2013/04/creating-a-pentaho-reporting-server-ubuntu-12-04-openerp/  
http://www.baconconsult.eu/home/our-products/openerp/openerp-printing/reporting---pentaho-and-openerp/pentaho-reporting-module-installation-and-configuration

**Comment by richard-willdooit** [comment]
@alimanager 
We have a pre-built war file on the website to use.  Why not just use that??

http://cloud1.willowit.com.au/dist/pentaho-reports-for-openerp.war

**Comment by alimanager** [comment]
![capture du 2015-08-17 09 35 10](https://cloud.githubusercontent.com/assets/13826468/9300272/6a681622-44c4-11e5-888c-2339f34a6298.png)
i add war to apache, in the result  i have this error , it normall???

**Comment by richard-willdooit** [comment]
@alimanager 

That appears to be normal.  You cannot go directly to that URL.

You should be able to check if everything is up and running at:

http://localhost:8080/manager/html

Also, by checking the log file (catalina.out) - wherever that is being captured (we normally send it to /var/log/tomcat

Richard
