### ISSUE TITLE
Error 111 conection refused Pentaho in Odoo 8

### ISSUE THREAD

**Issue by FranTobar** [WilldooIT/Pentaho-reports-for-OpenERP#227]
Hi, I install the plug- in Pentaho Report Odoo and create a report with Pentaho Report Designer , but when trying to print the report from Odoo I get the following error: File " /usr/lib/python2.7/socket . py " , line 571, in create_connection raise err error: [ Errno 111] Connection refused .
I think this is due to the parameter setups for Pentaho within Odoo .
Anyone have any solution? Or you know how to set starting parameters for the correct Connection?
Thank you!

**Comment by richard-willdooit** [comment]
@frantobar

Have a bit of a browse through the module description - the description from **openerp**.py for pentaho_reports.

Settings/Customization/System Parameters in Odoo is where to set the parameters.

Is it an object based or an sql based report?  The parameters needed differ depending.

**Comment by richard-willdooit** [comment]
Oh, and if you have encrypted passwords, ensure you install pentaho_reports_auth_crypt

**Comment by prasathbala** [comment]
I too have the same problem and am having sql based report using odoo community version 9.0
![44](https://cloud.githubusercontent.com/assets/10784198/22581974/deb7a9fc-ea09-11e6-8afe-9c430963678d.png)

**Comment by prasathbala** [comment]
This issue is same as https://github.com/WilldooIT/Pentaho-reports-for-OpenERP/issues/49. But what is the parameter you are mentioning here.

**Comment by prasathbala** [comment]
<data:sql-datasource xmlns:data="http://jfreereport.sourceforge.net/namespaces/datasources/sql">
  <data:config/>
  <data:connection>
    <data:driver>org.postgresql.Driver</data:driver>
    <data:url>jdbc:postgresql://192.168.0.134:5432/Ten10Reports</data:url>
    <data:properties>
      <data:property name="user">tempuser</data:property>
      <data:property name="password">encrypted:</data:property>
      <data:property name="::pentaho-reporting::port">5432</data:property>
      <data:property name="::pentaho-reporting::name">Odoo DB</data:property>
      <data:property name="::pentaho-reporting::database-name">testreports</data:property>
      <data:property name="::pentaho-reporting::hostname">192.168.0.134</data:property>
      <data:property name="::pentaho-reporting::database-type">POSTGRESQL</data:property>
    </data:properties>
  </data:connection>
  <data:query-definitions>
    <data:query name="Query 1">
      <data:static-query>Select  
	a.date as WORKEDDATE, 
	f.workingdays as WORKINGDAYS,
	c.name as EMPLOYEENAME, 
	d.name as COMPANY, 
	e.name as PROJECT, 
	a.name as DESCRIPTION, 
	a.incident_no as INCIDENTNO, 
	a.activity_type as ACTIVITY, 
	a.unit_amount as HRS
from account_analytic_line a
left join res_users b on a.user_id = b.id
left join res_partner c on b.partner_id = c.id
left join res_company d ON  a.company_id = d. id 
left join account_analytic_account e ON a.account_id = e.id
right join tpt_working_days f on to_char(a.date, 'Month') = f.month
order by a.date</data:static-query>
    </data:query>
  </data:query-definitions>
</data:sql-datasource>

This is my data connection and it is working in Pentaho Report Designer.
