### ISSUE TITLE
it not show "pentaho report option in odoo"

### ISSUE THREAD

**Issue by kartikdanidhariya** [WilldooIT/Pentaho-reports-for-OpenERP#228]
hi i want to use pentaho report in odoo 
i copy your repo and put in to addons  in odoo setup after i "update module list" and after i install all five module of pantaho
1)pentaho_report_schedular
2)pentaho_report_schedular_selection_sets
3)pentaho_report_selection_sets
4)pentaho_reports
5)pentaho_reports_auth_crypt

after that it make not effect ,
not show any option like "pentaho report" in action
i want to know how  create report in pentaho in odoo 8.0 (windows 7)

**Comment by richard-willdooit** [comment]
@kartikdanidhariya 

The version 8 behaviour is that it modifies the standard report actions.

Create (or modify) an existing report (Settings > Actions > Reports) and for "Report Type" you should have the option for "Pentaho".

Let us know if that is not the case.  You only need the basic "pentaho_reports" for this to show.
