### ISSUE TITLE
com.willowit.reporting.PentahoRenderer: URI can't be null

### ISSUE THREAD

**Issue by sm2x** [WilldooIT/Pentaho-reports-for-OpenERP#231]
I've updated the war file and openerp-modules via WillowIT github, Report Designer is version 5.4...
from thereon I keep on getting the above error on both odoo and pentaho server logs.
-  OS Ubuntu 14.04
-  Odoo version 8
-  installed modules:  pentaho_reports and pentaho_reports_auth_crypt

![warning-message](https://cloud.githubusercontent.com/assets/6595333/10841600/fac09d7c-7efb-11e5-8629-0a2af99a3f0a.png)

**Comment by richard-willdooit** [comment]
@sm2x 

xmlrpclib.Fault is very generic - can you give me more details of what the tomcat log is showing (catalina.out)?

**Comment by richard-willdooit** [comment]
@sm2x 

Hey, please see #235

**Comment by richard-willdooit** [comment]
@sm2x - I am closing this issue?!?
