### ISSUE TITLE
Record pentaho report on Odoo and send the report in mail

### ISSUE THREAD

**Issue by kazacube-agnaoui** [WilldooIT/Pentaho-reports-for-OpenERP#236]
hello I would like to know the syntax of the declaration record report-pentaho, in a xml file

example does not work:

<? xml version = "1.0" encoding = "utf-8"?>
<openerp>
     <data>
         <report
             id = "report_sale_order_pentaho"
             string = "Quotation / Order Pentaho"
             model = "sale.order"
             report_type = "pentaho"
             file = "report.report_saleorder.prpt"
             name = "sale.report_saleorder"
         />
     </ data>
</ openerp>

and attach the report pentaho to a message in order to send to a client (sale order)

 good to you

**Comment by diggy128** [comment]
This is almost completely wrong.
Is should be like:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<openerp>
    <data>
        <record id="mrp_bom_cost" model="ir.actions.report.xml">
            <field name="name">Κοστολόγιο</field>
            <field name="report_name">mrp.bom.cost</field>
            <field name="model">x</field>
            <field name="auto" eval="False"/>
            <field name="rml">mrp_extension/report/bom_cost.prpt</field>
            <field name="is_pentaho_report" eval="True"/>
            <field name="pentaho_report_model_id" ref="mrp.model_mrp_bom"/>
            <field name="pentaho_report_output_type">pdf</field>
            <field name="pentaho_filename">mrp_extension/report/bom_cost.prpt</field>
            <field name="pentaho_load_file" eval="True"/>
        </record>
    </data>
</openerp>
```

**Comment by kazacube-agnaoui** [comment]
thank's brother...
