### ISSUE TITLE
Odoo - style formatting

### ISSUE THREAD

**Issue by disna-sistemas** [WilldooIT/Pentaho-reports-for-OpenERP#241]
I have a report with a field I want to force its font style to Liberation Sans.

In common section I have:
- rich-text-type:  text/html

In query-metadata section:
- style-format: True
- enable-style-font: True
- enable-style-color: True

I set font-family = Liberation Sans for this field, and I change its color but the result is the formatting style is the one that comes from de data-query

Thanks in advance,

Victor Martin

**Comment by diggy128** [comment]
The HTML parser in Pentaho is half-baked  and very picky as it supports a limited CSS subset.
Thus, what you are trying will simply not work.

I've had the same problem couldn't solve it completely. See [here](http://forums.pentaho.com/showthread.php?170009-Change-style-of-a-HTML-Rich-Text-field-in-the-Reporting-Tool&p=394252#post394252) so I had to reformat the html to RTF in my openERP module (which is a lot harder to handle, but prints nicely in PRD).

**Comment by richard-willdooit** [comment]
@diggy128 Thanks for addressing this.  What Pentaho can and can't do is well beyond the scope of this project.

@disna-sistemas Does it work in the designer and not when deployed?  If it works when running through the designer, then the problem may simply be font availability at run time?

**Comment by disna-sistemas** [comment]
@richard-willowit Exactly, it works when running through the designer, and also works in Odoo when the report output format is set to HTML instead of PDF

**Comment by richard-willdooit** [comment]
@disna-sistemas Unfortunately, it is then relating to Pentaho engine and rendering behaviour, and is probably best dealt with on [forums.pentaho.com](http://forums.pentaho.com/).
