### ISSUE TITLE
Calling report from wizard view

### ISSUE THREAD

**Issue by fnegrini** [WilldooIT/Pentaho-reports-for-OpenERP#243]
Hello,

I have created an normal odoo wizard to collect the parameters and select the ids to pass to penhtaho report. 

The 'process' method (called by the wizard button), runs the search method and gets the ids correctly. The pentaho report is called correctly and downloaded, but show no records in PDF. This is because I can't link my Ids to pentaho reports. I'm trying to do like this (Results contains the ids for the report):

```
    data['ids'] = Results
    data['model'] = 'the.model.report'

    return {
        'type': 'ir.actions.report.xml',
        'report_name': 'pentaho.report.name',
        'data': data,
        'nodestroy' : True
    }
```

How can I link my ids (in Results variable) to the pentaho ids?

Thanks,

**Comment by richard-willdooit** [comment]
In Pentaho, are you defining a parameter called ids?

Defining a parameter called ids with type "Integer" (Display Type = Multi Value List) is necessary.

Then, when you call the action, data is a dictionary which will need a key called "variables" with an entry called ids.

i.e.
data['output_type'] = 'pdf'
data['variables'] ={'ids': Results}

I am not sure why you are needing to put the model in the data?

**Comment by fnegrini** [comment]
Nevermind the model in the data... my mistake. I have created the ids parameters and linked to the id in the DataSource. I debuged and realized that calling the report this way::

```
return {
    'type': 'ir.actions.report.xml',
    'report_name': 'pentaho.report.name',
    'data': data,
    'nodestroy' : True
}
```

Is the problem. It is not setting the data to the report object. Is there another way to call the report by wizard?

**Comment by fnegrini** [comment]
Problem solved! The correct call is:

return {
    'type': 'ir.actions.report.xml',
    'report_name': 'pentaho.report.name',
    'datas': data,
    'nodestroy' : True
}

The variable name is 'datas', not 'data' as I was calling. Report is running perfectly!

**Comment by aitorbouzas** [comment]
@richard-willdooit 

Sorry for the last reply (deleted it because I solved it). I manage to print a report like this, but now I need to make an job in Odoo that gets the PDF for each id to upload it to a FTP. Any tip on that?
I'm passing 2 date parameters to the report + the id that I need.
