### ISSUE TITLE
Parameter Error

### ISSUE THREAD

**Issue by davidtanadi** [WilldooIT/Pentaho-reports-for-OpenERP#247]
Hello,
I have error when try to generate report using configuration :
- Main Query filter by Parameter A AND Parameter B
- Parameter A filter by user_id (object)
- Parameter B
  (when I try to change user_id to integer , there is no problem)

using : ODOO 8, Pentaho 5.2 , Tomcat 7.0.52 

any solution ?

**Comment by richard-willdooit** [comment]
@davidtanadi 

I am sorry, I cannot work out what you are asking?  Yes, a parameter can be filtered by user_id (or data ids, or context), but a parameter cannot be filtered by another parameter, as the report is only called twice - once to get the prompted parameters and their valid selections, and once to run the report.

Could you provide more information about what your problem actually is?

**Comment by davidtanadi** [comment]
@richard-willowit ok thx.. maybe I should try using context to filter my report

**Comment by HaiPham1989** [comment]
@richard-willowit  you can upgrade pentaho reports add ons to filter a parameter from other parameter. In my opinion, This is a important upgrade pentaho reports addons
Thanks!

**Comment by richard-willdooit** [comment]
@HaiPham1989 Yes, it would be very useful.  It would require a fair architectural re-think, though.  The parameters are all evaluated and their selections determined by one call to pentaho - we would effectively have to call after each parameter was entered, and then re-generate the prompt wizard...

The proper answer would involve selectively calling Pentaho in an on-the-fly generated onchange, and then updating the list of valid options, which are not presented as a "selection" but as a proper M2O.
