### ISSUE TITLE
Odoo 9 and Sql Queries

### ISSUE THREAD

**Issue by mrparadies** [WilldooIT/Pentaho-reports-for-OpenERP#250]
I am successfully able to run reports in ODOO 9 created with the Pentaho OPENERP Data Access method.  However I am running into an issue with utilizing SQL queries.  I have created a report with a very simple query on stock.picking:

SELECT stock_picking.name as ShipID, 
stock_picking.id

FROM public.stock_picking stock_picking

WHERE stock_picking.id in ($(ids))

I am using the odoo postgres user and have it set in the parameters.  Also I am able to query data in the report designer if I change the where clause.  When I upload and try to run this report in ODOO I get the following error:

![image](https://cloud.githubusercontent.com/assets/17574418/13678741/dad4930c-e6b5-11e5-858f-f8eee04b30d6.png)

Am I missing something in the process or has the where statement with ids changed?  Let me know if you need any additional information and thanks for your help.

**Comment by mrparadies** [comment]
<class 'xmlrpclib.Fault'>, <Fault 0: 'Failed to invoke method execute in class com.willowit.reporting.PentahoRenderer: Failed at query: SELECT sale_order.name as ShipID, \nsale_order.id\n\nFROM public.sale_order sale_order\n\n\nWHERE sale_order.id in ($(ids))\n\n'>, <traceback object at 0x7f8e3848f248>)

**Comment by mrparadies** [comment]
Also, I am using TomCat7, java 1.7.X, centos7 and installed via war file.

**Comment by richard-willdooit** [comment]
@mrparadies 

You need to define a parameter inside Pentaho for the ids to go in to.  Under "Data", create a parameter called ids, value type Integer, display type Mutli Value list, and make sure validate values is turned off.  That should be all you need.

For testing reports, I often create an additional data source (e.g. "SalesOrders", "select id,name from sale_order") and then associate that data source with the ids parameter (Query = "SaleOrders", value="id" DisplayName='name'), so I can choose orders for testing.  This additional query will be ignored at final deployment inside Odoo.

**Comment by mrparadies** [comment]
Oh man I knew I was missing something.  That did it.  Thank you so much for your help on this great product!

**Comment by richard-willdooit** [comment]
@mrparadies NP.

**Comment by mrparadies** [comment]
Well I thought I had it but realized today I actually was testing the wrong file.  I still am getting the same error after adding the parameter.  Heres my query:
![image](https://cloud.githubusercontent.com/assets/17574418/13705023/8691486c-e764-11e5-978e-03cb9f530a29.png)

And heres my Parameter:
![image](https://cloud.githubusercontent.com/assets/17574418/13705138/16a8d5aa-e765-11e5-8f81-c917404254d7.png)

I do notice that after I enter the parameter, click ok and go back into it, it seems to loss the connection to the "Packing Slip" query.  What else am I missing?  Sorry for the confusion.

Thanks for your help.

**Comment by richard-willdooit** [comment]
@mrparadies 
Your parameter should not depend on ids - it is a dummy that will not be executed  - just remove the "WHERE" clause.  The association of the query with the parameter is purely so you can test the report inside the designer.

If this doesn't get it for you, email the prpt to me.
