### ISSUE TITLE
Get user running the report error

### ISSUE THREAD

**Issue by dungnm8** [WilldooIT/Pentaho-reports-for-OpenERP#252]
Hi Richard,

First: thanks for providing the Odoo 9 version of this fantastic add-on! Works as expected with one exception (so far).

I have error when try function current_user() get user running the report
- **current_user() returns integer - The user id of the user running the report.**

https://github.com/WillowIT/Pentaho-reports-for-OpenERP/wiki/Parameter-Set-Selection-Functions

**Comment by richard-willdooit** [comment]
@Dungnm8 I am guessing you have this sorted?
