### ISSUE TITLE
Invoice report repeated values

### ISSUE THREAD

**Issue by diegomor** [WilldooIT/Pentaho-reports-for-OpenERP#257]
First, thanks for this update to odoo 9.

I'm creating an invoice report in odoo 9, everything works fine except the details section inside the group header, the problem I'm facing is that the in details section I get repeated 3 times each line fetched from account.invoice.line.

Do you know what I should review to get this solved?

**Comment by richard-willdooit** [comment]
@diegomor Is it an object report or SQL?  Does it work running through the designer and fail when loaded?

If it is object report, are you at all referencing any child values from account.invoice.line?  Particularly one2many or many2many (e.g. tax?)  Even if you are not printing their values, referencing them in the query will cause the return of the data (e.g. if you reference the tax and there are 3 taxes, then the line will be effectively returned 3 times).

This particularly can be a "gotcha" when reporting stock moves and retrieving quant or lot information.

Anyway, that's a start...

**Comment by diegomor** [comment]
@richard-willowit It's object report.
Actually I fetched taxes fields but I don't use them, now I can't figure out how to remove these fields from Search Fields menu in OpenERP data access.

**Comment by diegomor** [comment]
@richard-willowit Now, I figured it out using Supr, removed those fields and works fine!
Thanks a lot!
