### ISSUE TITLE
Direct printing with Pentaho reports

### ISSUE THREAD

**Issue by morphace** [WilldooIT/Pentaho-reports-for-OpenERP#259]
Hi Guys,

I wonder, if there's a way how to directly print a report to the printer (without going the deviation via PDF). I read that Pentaho generally is able to do so, but I couldn't find anything for the Odoo integration...

Thanks!
Markus

**Comment by diggy128** [comment]
You should check base_report_to_printer module. It allows you to directly print ANY report from Odoo.
I've been using it for more than a year with no problem. You still get the PDF downloaded but the pages are also sent to a CUPS printer.

**Comment by morphace** [comment]
Hey thanks, I saw the add-on, but I thought it would only work with QWeb reports. It works perfectly with Pentaho reports as well, with the exception that the PDF is generated anyway (any idea how to avoid this?). The add-on is for V8, but it's easy to make it work with V9. If anybody needs support, feel free to contact me.
