### ISSUE TITLE
Pentaho SQl Query

### ISSUE THREAD

**Issue by sebytza05** [WilldooIT/Pentaho-reports-for-OpenERP#265]
Hey,

I have installed on my Odoo 8 on Ubuntu 14.04  next things:

http://www.baconconsult.eu/home/our-products/openerp/openerp-printing/reporting---pentaho-and-openerp/pentaho-java-report-server

https://www.digitalocean.com/community/tutorials/how-to-install-apache-tomcat-7-on-ubuntu-14-04-via-apt-get

I got also installed in odoo 8 ,the pentaho:
![1](https://cloud.githubusercontent.com/assets/19728451/15776194/d53838e2-298e-11e6-85fd-8e6fb850994a.png)

In system parameters i got it :
![2](https://cloud.githubusercontent.com/assets/19728451/15776203/e48a326e-298e-11e6-9564-d305dec52a42.png)

Also i deployed the jar on server:
![3](https://cloud.githubusercontent.com/assets/19728451/15776214/f2b2561e-298e-11e6-9509-80c59abc63a0.png)

When i import objects reports from pentaho report degisner 5.3 works perfect in odoo 8.

When i import SQL reports from pentaho report designer 5.3, everytime i got the error Uncaught SyntaxError: Unexpected end of JSON input.

![unnamed](https://cloud.githubusercontent.com/assets/19728451/15776225/fff21ee0-298e-11e6-86f2-e26f86089f61.png)

Even for a simple query like,select name from res_partner not works.

I think i miss something,but i do not know what it is,if ya guys could help me i will be so glad.

Thanks

Regards,
Sebastian

**Comment by sebytza05** [comment]
One more thing:
The reports  SQL query works perfect in Pentaho preview,but when i import it in Odoo 8 always same error:Uncaught SyntaxError: Unexpected end of JSON input.

**Comment by sebytza05** [comment]
My pentaho report designer is 5.0.1 -stable
Sorry

**Comment by sebytza05** [comment]
Finnally ,i fixed it:
1.I added in my pg_hba,the host of the server(host      all     all     192.168.2.136/32     md5).
2.I added in System Parameters:
            -   pentaho.postgres.login : db_user(from openerp-server.conf)
            -   pentaho.postgres.password : db_password(from openerp-server.conf)
Cheers

**Comment by richard-willdooit** [comment]
@sebytza05 Glad you sorted it out.  Sorry, I have been away and unable to answer.  Cheers.
