### ISSUE TITLE
Pentaho Renderer error

### ISSUE THREAD

**Issue by diegomor** [WilldooIT/Pentaho-reports-for-OpenERP#270]
Hi
I have created new module with new table 'cfdi.metodo.pago' and also created a report making reference to 'cfdi.metodo.pago' table and works fine on local machine. 

I tried to replicate on production server, I installed new module, uploaded .prpt file and restarted odoo server, but got this error message:

Fault: 

```
<Fault 0: "Failed to invoke method execute in class com.willowit.reporting.PentahoRenderer:    Could not find model with name 'cfdi.metodo.pago'">
```

I have checked using psql that table actually exists and it does. I can't figure out this error.

Does anyone have any suggestions?

Thanks in advance!

**Comment by richard-willdooit** [comment]
@diegomor 

When your instance of odoo calls the pentaho reporter, it passes to it all the details about how to back communicate with the correct server and database.

So, first thing is to check all the system parameters.  

```
pentaho.openerp.xml.interface
pentaho.openerp.xml.port
pentaho.postgres.host
pentaho.postgres.port
pentaho.postgres.login
pentaho.postgres.password
```

Sometimes, a server restart is not enough, as the client may have cached information about the action?  (probably not in this case...)

Does the tomcat log file (catalina.out) shed any light?

**Comment by richard-willdooit** [comment]
Oh, it could be worth making a report that draws data from res.partner, or something that would be on all databases, that would help identify if it is communicating with the correct db?

**Comment by aitorbouzas** [comment]
@diegomor How was this issue solved? I'm having a similar issue with a model "fleet.vechile" (that existed from long time ago).
My report was working correctly with that fleet.vechile thing, but all of sudden now it's not working...
