### ISSUE TITLE
pentaho report for open erp for odoo 10

### ISSUE THREAD

**Issue by crane134a** [WilldooIT/Pentaho-reports-for-OpenERP#279]
Hi, Mr. Richard's

I have been using pentaho-report-for-OpenERP since odoo odoo 8 and 9, but in this odoo 10 pentaho-report-for-OpenERP can not be used. when will the updated modules to be used in odoo10. 

thank you

**Comment by jiangzhixiao** [comment]
it seems to do  big refactorings work!

**Comment by AngelinaWessonFritzsche** [comment]
Hi,
me and my company also waiting for using the pentaho reports in odoo 10.
Can anybody tell me how long we have to wait until we can use it in odoo 10 (the report designer and the odoo addon)?
Are you working on it?

Thank you
Yours Angie

**Comment by mrparadies** [comment]
I would be interested in this information as well.

**Comment by morphace** [comment]
+1

**Comment by morphace** [comment]
any plans?

**Comment by richard-willdooit** [comment]
@morphace @mrparadies @AngelinaWessonFritzsche @crane134a @jiangzhixiao 

Hi all.

I have begun it....

**Comment by morphace** [comment]
@richard-willdooit Cool! Thanks a lot for your work...

I guess, you will have to work on the Java part as well? If so, it would be phantastic, if we could find a solution for the i18n/Locale (see #263) issues as well...

**Comment by richard-willdooit** [comment]
@morphace @mrparadies @AngelinaWessonFritzsche @crane134a @jiangzhixiao

Announcing First Cut v10 - Note that only SQL queries are supported at the moment - See the readme for what state this is in.  The rest will have to wait until the new year, unfortunately.

[https://github.com/WilldooIT/Pentaho-Odoo](https://github.com/WilldooIT/Pentaho-Odoo)

**Comment by jiangzhixiao** [comment]
@richard-willdooit Great job ! thanks a lot richard

**Comment by sirhaeck** [comment]
Hi,
pdf created under odoo10 raises error in adobe reader when sending to printer (printing works without error message with Foxit). Any idea how to solve this?

thx

**Comment by sirhaeck** [comment]
Hi all,
solved.
