### ISSUE TITLE
Descending sorting

### ISSUE THREAD

**Issue by disna-sistemas** [WilldooIT/Pentaho-reports-for-OpenERP#282]
Hi, 
I want to sort a report by a float field in descending order.
I have tried the following with no success:
- creating a group [amount desc]
- creating a group [amount*-1]

Thanks in advance.

**Comment by onduex** [comment]
Hi, you can find in query
<img width="631" alt="sort" src="https://cloud.githubusercontent.com/assets/7617305/22379126/5e3d1fb0-e4b8-11e6-9a22-ef786465e33a.PNG">

**Comment by richard-willdooit** [comment]
@onduex @disna-sistemas 

Thanks for addressing this - it slipped me by.
