### ISSUE TITLE
HTTP Status 405 - HTTP method GET is not supported by this URL

### ISSUE THREAD

**Issue by inouzuka** [WilldooIT/Pentaho-reports-for-OpenERP#285]
While I am accessing http://localhost:8080/pentaho-reports-for-openerp/, I caught with that error.
I am using openjdk-8,
tomcat version 8,
odoo9c,
Everything is fine, I am using .war file which is available here before and deployment it with smooth.
I am new at using odoo and pentaho too.
Thanks.

**Comment by richard-willdooit** [comment]
@inouzuka That actually sounds correct.  The url will not be accessed by the odoo server using "get", so that is not a problem.  You cannot simply put the url in a browser and go to it.  You need to go to http://localhost:8080 and then go in to the manager app to find the service.
