### ISSUE TITLE
Unable to resolve dependencies

### ISSUE THREAD

**Issue by schout-it** [WilldooIT/Pentaho-reports-for-OpenERP#295]
when building the version80 I get the following error (ubuntu 16.04 and docker image with java:7 image)
If I take a look at ivy-nexus.pentaho.org, I don't see the SNAPSHOT image.
Tried changing to 5.4.0.5-151 but the error persists.

trace:
[ivy:resolve] :: Ivy 2.2.0 - 20100923230623 :: http://ant.apache.org/ivy/ ::
[ivy:resolve] :: loading settings :: url = file:/home/rod/pentaho-odoo/Pentaho-reports-for-OpenERP/java_server/ivysettings.xml
[ivy:resolve] :: resolving dependencies :: com.willowit#pentaho-reports-for-openerp;8.0.3
[ivy:resolve]   confs: [default_internal]
[ivy:resolve] :: resolution report :: resolve 21953ms :: artifacts dl 0ms
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        | default_internal |   12  |   0   |   0   |   0   ||   0   |   0   |
        ---------------------------------------------------------------------
[ivy:resolve]
[ivy:resolve] :: problems summary ::
[ivy:resolve] :::: WARNINGS
[ivy:resolve]           module not found: pentaho-reporting-engine#pentaho-reporting-engine-classic-core;5.4-SNAPSHOT
[ivy:resolve]   ==== local: tried
[ivy:resolve]     /home/rod/.ivy2/local/pentaho-reporting-engine/pentaho-reporting-engine-classic-core/5.4-SNAPSHOT/ivys/ivy.xml
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-classic-core;5.4-SNAPSHOT!pentaho-reporting-engine-classic-core.jar:
[ivy:resolve]     /home/rod/.ivy2/local/pentaho-reporting-engine/pentaho-reporting-engine-classic-core/5.4-SNAPSHOT/jars/pentaho-reporting-engine-classic-core-5.4-SNAPSHOT.jar
[ivy:resolve]   ==== pentaho-ivy: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-core/5.4-SNAPSHOT/pentaho-reporting-engine-classic-core-5.4-SNAPSHOT.ivy.xml
[ivy:resolve]   ==== pentaho-mvn: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-core/5.4-SNAPSHOT/pentaho-reporting-engine-classic-core-5.4-SNAPSHOT.pom
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-classic-core;5.4-SNAPSHOT!pentaho-reporting-engine-classic-core.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-core/5.4-SNAPSHOT/pentaho-reporting-engine-classic-core-5.4-SNAPSHOT.jar
[ivy:resolve]   ==== public-maven: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-core/5.4-SNAPSHOT/pentaho-reporting-engine-classic-core-5.4-SNAPSHOT.pom
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-classic-core;5.4-SNAPSHOT!pentaho-reporting-engine-classic-core.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-core/5.4-SNAPSHOT/pentaho-reporting-engine-classic-core-5.4-SNAPSHOT.jar
[ivy:resolve]           module not found: pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions;5.4-SNAPSHOT
[ivy:resolve]   ==== local: tried
[ivy:resolve]     /home/rod/.ivy2/local/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions/5.4-SNAPSHOT/ivys/ivy.xml
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions;5.4-SNAPSHOT!pentaho-reporting-engine-classic-extensions.jar:
[ivy:resolve]     /home/rod/.ivy2/local/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions/5.4-SNAPSHOT/jars/pentaho-reporting-engine-classic-extensions-5.4-SNAPSHOT.jar
[ivy:resolve]   ==== pentaho-ivy: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-5.4-SNAPSHOT.ivy.xml
[ivy:resolve]   ==== pentaho-mvn: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-5.4-SNAPSHOT.pom
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions;5.4-SNAPSHOT!pentaho-reporting-engine-classic-extensions.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-5.4-SNAPSHOT.jar
[ivy:resolve]   ==== public-maven: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-5.4-SNAPSHOT.pom
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions;5.4-SNAPSHOT!pentaho-reporting-engine-classic-extensions.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-5.4-SNAPSHOT.jar
[ivy:resolve]           module not found: pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions-scripting;5.4-SNAPSHOT
[ivy:resolve]   ==== local: tried
[ivy:resolve]     /home/rod/.ivy2/local/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-scripting/5.4-SNAPSHOT/ivys/ivy.xml
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions-scripting;5.4-SNAPSHOT!pentaho-reporting-engine-classic-extensions-scripting.jar:
[ivy:resolve]     /home/rod/.ivy2/local/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-scripting/5.4-SNAPSHOT/jars/pentaho-reporting-engine-classic-extensions-scripting-5.4-SNAPSHOT.jar
[ivy:resolve]   ==== pentaho-ivy: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-scripting/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-scripting-5.4-SNAPSHOT.ivy.xml
[ivy:resolve]   ==== pentaho-mvn: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-scripting/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-scripting-5.4-SNAPSHOT.pom
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions-scripting;5.4-SNAPSHOT!pentaho-reporting-engine-classic-extensions-scripting.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-scripting/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-scripting-5.4-SNAPSHOT.jar
[ivy:resolve]   ==== public-maven: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-scripting/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-scripting-5.4-SNAPSHOT.pom
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions-scripting;5.4-SNAPSHOT!pentaho-reporting-engine-classic-extensions-scripting.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-scripting/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-scripting-5.4-SNAPSHOT.jar
[ivy:resolve]           module not found: pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions-drill-down;5.4-SNAPSHOT
[ivy:resolve]   ==== local: tried
[ivy:resolve]     /home/rod/.ivy2/local/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-drill-down/5.4-SNAPSHOT/ivys/ivy.xml
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions-drill-down;5.4-SNAPSHOT!pentaho-reporting-engine-classic-extensions-drill-down.jar:
[ivy:resolve]     /home/rod/.ivy2/local/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-drill-down/5.4-SNAPSHOT/jars/pentaho-reporting-engine-classic-extensions-drill-down-5.4-SNAPSHOT.jar
[ivy:resolve]   ==== pentaho-ivy: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-drill-down/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-drill-down-5.4-SNAPSHOT.ivy.xml
[ivy:resolve]   ==== pentaho-mvn: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-drill-down/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-drill-down-5.4-SNAPSHOT.pom
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions-drill-down;5.4-SNAPSHOT!pentaho-reporting-engine-classic-extensions-drill-down.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-drill-down/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-drill-down-5.4-SNAPSHOT.jar
[ivy:resolve]   ==== public-maven: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-drill-down/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-drill-down-5.4-SNAPSHOT.pom
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions-drill-down;5.4-SNAPSHOT!pentaho-reporting-engine-classic-extensions-drill-down.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-drill-down/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-drill-down-5.4-SNAPSHOT.jar
[ivy:resolve]           module not found: pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions-toc;5.4-SNAPSHOT
[ivy:resolve]   ==== local: tried
[ivy:resolve]     /home/rod/.ivy2/local/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-toc/5.4-SNAPSHOT/ivys/ivy.xml
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions-toc;5.4-SNAPSHOT!pentaho-reporting-engine-classic-extensions-toc.jar:
[ivy:resolve]     /home/rod/.ivy2/local/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-toc/5.4-SNAPSHOT/jars/pentaho-reporting-engine-classic-extensions-toc-5.4-SNAPSHOT.jar
[ivy:resolve]   ==== pentaho-ivy: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-toc/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-toc-5.4-SNAPSHOT.ivy.xml
[ivy:resolve]   ==== pentaho-mvn: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-toc/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-toc-5.4-SNAPSHOT.pom
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions-toc;5.4-SNAPSHOT!pentaho-reporting-engine-classic-extensions-toc.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-toc/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-toc-5.4-SNAPSHOT.jar
[ivy:resolve]   ==== public-maven: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-toc/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-toc-5.4-SNAPSHOT.pom
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions-toc;5.4-SNAPSHOT!pentaho-reporting-engine-classic-extensions-toc.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-toc/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-toc-5.4-SNAPSHOT.jar
[ivy:resolve]           module not found: pentaho-reporting-engine#pentaho-reporting-engine-wizard-core;5.4-SNAPSHOT
[ivy:resolve]   ==== local: tried
[ivy:resolve]     /home/rod/.ivy2/local/pentaho-reporting-engine/pentaho-reporting-engine-wizard-core/5.4-SNAPSHOT/ivys/ivy.xml
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-wizard-core;5.4-SNAPSHOT!pentaho-reporting-engine-wizard-core.jar:
[ivy:resolve]     /home/rod/.ivy2/local/pentaho-reporting-engine/pentaho-reporting-engine-wizard-core/5.4-SNAPSHOT/jars/pentaho-reporting-engine-wizard-core-5.4-SNAPSHOT.jar
[ivy:resolve]   ==== pentaho-ivy: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-wizard-core/5.4-SNAPSHOT/pentaho-reporting-engine-wizard-core-5.4-SNAPSHOT.ivy.xml
[ivy:resolve]   ==== pentaho-mvn: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-wizard-core/5.4-SNAPSHOT/pentaho-reporting-engine-wizard-core-5.4-SNAPSHOT.pom
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-wizard-core;5.4-SNAPSHOT!pentaho-reporting-engine-wizard-core.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-wizard-core/5.4-SNAPSHOT/pentaho-reporting-engine-wizard-core-5.4-SNAPSHOT.jar
[ivy:resolve]   ==== public-maven: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-wizard-core/5.4-SNAPSHOT/pentaho-reporting-engine-wizard-core-5.4-SNAPSHOT.pom
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-wizard-core;5.4-SNAPSHOT!pentaho-reporting-engine-wizard-core.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-wizard-core/5.4-SNAPSHOT/pentaho-reporting-engine-wizard-core-5.4-SNAPSHOT.jar
[ivy:resolve]           module not found: pentaho-reporting-engine#pentaho-reporting-engine-legacy-charts;5.4-SNAPSHOT
[ivy:resolve]   ==== local: tried
[ivy:resolve]     /home/rod/.ivy2/local/pentaho-reporting-engine/pentaho-reporting-engine-legacy-charts/5.4-SNAPSHOT/ivys/ivy.xml
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-legacy-charts;5.4-SNAPSHOT!pentaho-reporting-engine-legacy-charts.jar:
[ivy:resolve]     /home/rod/.ivy2/local/pentaho-reporting-engine/pentaho-reporting-engine-legacy-charts/5.4-SNAPSHOT/jars/pentaho-reporting-engine-legacy-charts-5.4-SNAPSHOT.jar
[ivy:resolve]   ==== pentaho-ivy: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-legacy-charts/5.4-SNAPSHOT/pentaho-reporting-engine-legacy-charts-5.4-SNAPSHOT.ivy.xml
[ivy:resolve]   ==== pentaho-mvn: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-legacy-charts/5.4-SNAPSHOT/pentaho-reporting-engine-legacy-charts-5.4-SNAPSHOT.pom
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-legacy-charts;5.4-SNAPSHOT!pentaho-reporting-engine-legacy-charts.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-legacy-charts/5.4-SNAPSHOT/pentaho-reporting-engine-legacy-charts-5.4-SNAPSHOT.jar
[ivy:resolve]   ==== public-maven: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-legacy-charts/5.4-SNAPSHOT/pentaho-reporting-engine-legacy-charts-5.4-SNAPSHOT.pom
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-legacy-charts;5.4-SNAPSHOT!pentaho-reporting-engine-legacy-charts.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-legacy-charts/5.4-SNAPSHOT/pentaho-reporting-engine-legacy-charts-5.4-SNAPSHOT.jar
[ivy:resolve]           module not found: pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions-openerp;5.4-SNAPSHOT
[ivy:resolve]   ==== local: tried
[ivy:resolve]     /home/rod/.ivy2/local/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-openerp/5.4-SNAPSHOT/ivys/ivy.xml
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions-openerp;5.4-SNAPSHOT!pentaho-reporting-engine-classic-extensions-openerp.jar:
[ivy:resolve]     /home/rod/.ivy2/local/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-openerp/5.4-SNAPSHOT/jars/pentaho-reporting-engine-classic-extensions-openerp-5.4-SNAPSHOT.jar
[ivy:resolve]   ==== pentaho-ivy: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-openerp/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-openerp-5.4-SNAPSHOT.ivy.xml
[ivy:resolve]   ==== pentaho-mvn: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-openerp/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-openerp-5.4-SNAPSHOT.pom
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions-openerp;5.4-SNAPSHOT!pentaho-reporting-engine-classic-extensions-openerp.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-openerp/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-openerp-5.4-SNAPSHOT.jar
[ivy:resolve]   ==== public-maven: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-openerp/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-openerp-5.4-SNAPSHOT.pom
[ivy:resolve]     -- artifact pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions-openerp;5.4-SNAPSHOT!pentaho-reporting-engine-classic-extensions-openerp.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-openerp/5.4-SNAPSHOT/pentaho-reporting-engine-classic-extensions-openerp-5.4-SNAPSHOT.jar
[ivy:resolve]           module not found: javax.servlet#servlet-api;2.5
[ivy:resolve]   ==== local: tried
[ivy:resolve]     /home/rod/.ivy2/local/javax.servlet/servlet-api/2.5/ivys/ivy.xml
[ivy:resolve]     -- artifact javax.servlet#servlet-api;2.5!servlet-api.jar:
[ivy:resolve]     /home/rod/.ivy2/local/javax.servlet/servlet-api/2.5/jars/servlet-api-2.5.jar
[ivy:resolve]   ==== pentaho-ivy: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/javax.servlet/servlet-api/2.5/servlet-api-2.5.ivy.xml
[ivy:resolve]   ==== pentaho-mvn: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/javax/servlet/servlet-api/2.5/servlet-api-2.5.pom
[ivy:resolve]     -- artifact javax.servlet#servlet-api;2.5!servlet-api.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar
[ivy:resolve]   ==== public-maven: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/javax/servlet/servlet-api/2.5/servlet-api-2.5.pom
[ivy:resolve]     -- artifact javax.servlet#servlet-api;2.5!servlet-api.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar
[ivy:resolve]           module not found: org.apache.xmlrpc#xmlrpc-server;3.1.3
[ivy:resolve]   ==== local: tried
[ivy:resolve]     /home/rod/.ivy2/local/org.apache.xmlrpc/xmlrpc-server/3.1.3/ivys/ivy.xml
[ivy:resolve]     -- artifact org.apache.xmlrpc#xmlrpc-server;3.1.3!xmlrpc-server.jar:
[ivy:resolve]     /home/rod/.ivy2/local/org.apache.xmlrpc/xmlrpc-server/3.1.3/jars/xmlrpc-server-3.1.3.jar
[ivy:resolve]   ==== pentaho-ivy: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/org.apache.xmlrpc/xmlrpc-server/3.1.3/xmlrpc-server-3.1.3.ivy.xml
[ivy:resolve]   ==== pentaho-mvn: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/org/apache/xmlrpc/xmlrpc-server/3.1.3/xmlrpc-server-3.1.3.pom
[ivy:resolve]     -- artifact org.apache.xmlrpc#xmlrpc-server;3.1.3!xmlrpc-server.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/org/apache/xmlrpc/xmlrpc-server/3.1.3/xmlrpc-server-3.1.3.jar
[ivy:resolve]   ==== public-maven: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/org/apache/xmlrpc/xmlrpc-server/3.1.3/xmlrpc-server-3.1.3.pom
[ivy:resolve]     -- artifact org.apache.xmlrpc#xmlrpc-server;3.1.3!xmlrpc-server.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/org/apache/xmlrpc/xmlrpc-server/3.1.3/xmlrpc-server-3.1.3.jar
[ivy:resolve]           module not found: org.apache.commons#commons-lang3;3.1
[ivy:resolve]   ==== local: tried
[ivy:resolve]     /home/rod/.ivy2/local/org.apache.commons/commons-lang3/3.1/ivys/ivy.xml
[ivy:resolve]     -- artifact org.apache.commons#commons-lang3;3.1!commons-lang3.jar:
[ivy:resolve]     /home/rod/.ivy2/local/org.apache.commons/commons-lang3/3.1/jars/commons-lang3-3.1.jar
[ivy:resolve]   ==== pentaho-ivy: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/org.apache.commons/commons-lang3/3.1/commons-lang3-3.1.ivy.xml
[ivy:resolve]   ==== pentaho-mvn: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.pom
[ivy:resolve]     -- artifact org.apache.commons#commons-lang3;3.1!commons-lang3.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
[ivy:resolve]   ==== public-maven: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.pom
[ivy:resolve]     -- artifact org.apache.commons#commons-lang3;3.1!commons-lang3.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
[ivy:resolve]           module not found: org.postgresql#postgresql;9.3-1102-jdbc4
[ivy:resolve]   ==== local: tried
[ivy:resolve]     /home/rod/.ivy2/local/org.postgresql/postgresql/9.3-1102-jdbc4/ivys/ivy.xml
[ivy:resolve]     -- artifact org.postgresql#postgresql;9.3-1102-jdbc4!postgresql.jar:
[ivy:resolve]     /home/rod/.ivy2/local/org.postgresql/postgresql/9.3-1102-jdbc4/jars/postgresql-9.3-1102-jdbc4.jar
[ivy:resolve]   ==== pentaho-ivy: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/org.postgresql/postgresql/9.3-1102-jdbc4/postgresql-9.3-1102-jdbc4.ivy.xml
[ivy:resolve]   ==== pentaho-mvn: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/org/postgresql/postgresql/9.3-1102-jdbc4/postgresql-9.3-1102-jdbc4.pom
[ivy:resolve]     -- artifact org.postgresql#postgresql;9.3-1102-jdbc4!postgresql.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/org/postgresql/postgresql/9.3-1102-jdbc4/postgresql-9.3-1102-jdbc4.jar
[ivy:resolve]   ==== public-maven: tried
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/org/postgresql/postgresql/9.3-1102-jdbc4/postgresql-9.3-1102-jdbc4.pom
[ivy:resolve]     -- artifact org.postgresql#postgresql;9.3-1102-jdbc4!postgresql.jar:
[ivy:resolve]     http://ivy-nexus.pentaho.org/content/groups/omni/org/postgresql/postgresql/9.3-1102-jdbc4/postgresql-9.3-1102-jdbc4.jar
[ivy:resolve]           ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]           ::          UNRESOLVED DEPENDENCIES         ::
[ivy:resolve]           ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]           :: pentaho-reporting-engine#pentaho-reporting-engine-classic-core;5.4-SNAPSHOT: not found
[ivy:resolve]           :: pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions;5.4-SNAPSHOT: not found
[ivy:resolve]           :: pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions-scripting;5.4-SNAPSHOT: not found
[ivy:resolve]           :: pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions-drill-down;5.4-SNAPSHOT: not found
[ivy:resolve]           :: pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions-toc;5.4-SNAPSHOT: not found
[ivy:resolve]           :: pentaho-reporting-engine#pentaho-reporting-engine-wizard-core;5.4-SNAPSHOT: not found
[ivy:resolve]           :: pentaho-reporting-engine#pentaho-reporting-engine-legacy-charts;5.4-SNAPSHOT: not found
[ivy:resolve]           :: pentaho-reporting-engine#pentaho-reporting-engine-classic-extensions-openerp;5.4-SNAPSHOT: not found
[ivy:resolve]           :: javax.servlet#servlet-api;2.5: not found
[ivy:resolve]           :: org.apache.xmlrpc#xmlrpc-server;3.1.3: not found
[ivy:resolve]           :: org.apache.commons#commons-lang3;3.1: not found
[ivy:resolve]           :: org.postgresql#postgresql;9.3-1102-jdbc4: not found
[ivy:resolve]           ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]
[ivy:resolve] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS

BUILD FAILED
/home/rod/pentaho-odoo/Pentaho-reports-for-OpenERP/java_server/build-res/subfloor.xml:685: The following error occurred while executing this line:
/home/rod/pentaho-odoo/Pentaho-reports-for-OpenERP/java_server/build-res/subfloor.xml:687: impossible to resolve dependencies:
        resolve failed - see output for details

Total time: 24 seconds

**Comment by yajo** [comment]
So how did you manage to fix this?

**Comment by schout-it** [comment]
I ended up using the war file and included it in de docker build dir
