### ISSUE TITLE
Issue with Pentaho Reports for OpenERP 7.0 Java Server

### ISSUE THREAD

**Issue by b-kannan** [WilldooIT/Pentaho-reports-for-OpenERP#30]
Error: The last step is not working. We get a HTTP 405 error on the URL:
type:  Status report
message: HTTP method GET is not supported by this URL
description: The specified HTTP method is not allowed for the requested resource (HTTP method GET is not supported by this URL).

Environment:
1. Ubuntu Linux 12.04 LTS Server on VirtualBox
2. Windows 8 Client with Google Chrome browser

! Get Pentaho-Reports-for-OpenERP from github
1. On the Browser, goto URL https://github.com/WillowIT/Pentaho-reports-for-OpenERP7.
2. Click on Zip
3. Pentaho-reports-for-OpenERP-master.zip will be downloaded to the local downloads folder.
4. Copy this file over to the Linux machine where OpenERP is installed (/opt/openerp folder)

! Install Java JDK 6
sudo apt-get install openjdk-6-jdk

! Make this the default java
sudo update-alternatives --config java

! Tomcat installation on ubuntu
sudo apt-get install tomcat7
sudo apt-get install tomcat7-docs
sudo apt-get install tomcat7-examples
sudo apt-get install tomcat7-admin

! Edit /etc/tomcat7/tomcat-users.xml and add the following after <tomcat-users> and before </tomcat-users>
sudo vi /etc/tomcat7/tomcat-users.xml
  < role rolename="admin-gui"/>
  < role rolename="manager-gui"/>
  < role rolename="manager-script"/>
  < role rolename="manager-jmx"/>
  < role rolename="manager-status"/>
  < user username="admin" password="admin" roles="admin-gui,manager-gui,manager-script,manager-jmx,manager-status"/>

! restart tomcat
sudo /etc/init.d/tomcat restart

! Check Tomcat Server and go into manager mode

! Deploy Pentaho-reports to tomcat application server
! Install Ant
sudo apt-get install ant

! Install subversion
sudo apt-get install subversion

mkdir /opt/openerp/ivy
cd /opt/openerp/ivy

! Install Ivy
svn co https://svn.apache.org/repos/asf/ant/ivy/core/trunk ivy
ant jar
sudo cp build/artifact/jars/ivy.jar /usr/share/ant/lib

! Extract Pentaho Reports

cd /opt/openerp
unzip Pentaho-reports-for-OpenERP-version70.zip
cd Pentaho-reports-for-OpenERP-version70

! Build Java Server for Pentaho Reports
cd javaserver
ant war

! The output war file “pentaho-reports-for-openerp.war” will be found in /opt/openerp/Pentaho-reports-for-OpenERP-version70/java_server/build/jar folder.

! Deploy “pentaho-reports-for-openerp.war” on Tomcat. If successful, the application will show up in Tomcat Manager (URL: http://<yourserver>:8080/manager). Follow Tomcat instructions for deploying/installing war file (the options are in the Manager).
! Pentaho Reports Java Application should now be available in http://<yourserver>:8080/pentaho-reports-for-openerp.

Error: The last step is not working. We get a HTTP 405 error on the URL:

**Comment by code-repository** [comment]
I get the same error (HTTP Status 405 - HTTP method GET is not supported by this URL) but the Pentaho server is actually running OK and I can run Pentaho reports from OpenERP OK.

I think the issue arises because your browser is doing an HTTP 'GET' on the URL but the Pentaho is using XML-RPC which is expecting an HTTP 'POST'. The 'GET' is not supported, hence the error message.

You can check if the Pentaho server is running by logging into the Tomcat manager (http://localhost:8080).

Hope this helps.

Doug. WillowIT.

**Comment by cormaza** [comment]
You most check if you compile war file with the same version of jre that
running tomcat instance, I have same problem in some machines with
difference versions, but when you have same version for example jre 6 and
jdk 6 don't have any problems

2013/1/17 b-kannan notifications@github.com

> Error: The last step is not working. We get a HTTP 405 error on the URL:
> type: Status report
> message: HTTP method GET is not supported by this URL
> description: The specified HTTP method is not allowed for the requested
> resource (HTTP method GET is not supported by this URL).
> 
> Environment:
> 1. Ubuntu Linux 12.04 LTS Server on VirtualBox
> 2. Windows 8 Client with Google Chrome browser
> 
> ! Get Pentaho-Reports-for-OpenERP from github
> 1. On the Browser, goto URL
>    https://github.com/WillowIT/Pentaho-reports-for-OpenERP7.
> 2. Click on Zip
> 3. Pentaho-reports-for-OpenERP-master.zip will be downloaded to the
>    local downloads folder.
> 4. Copy this file over to the Linux machine where OpenERP is installed
>    (/opt/openerp folder)
> 
> ! Install Java JDK 6
> sudo apt-get install openjdk-6-jdk
> 
> ! Make this the default java
> sudo update-alternatives --config java
> 
> ! Tomcat installation on ubuntu
> sudo apt-get install tomcat7
> sudo apt-get install tomcat7-docs
> sudo apt-get install tomcat7-examples
> sudo apt-get install tomcat7-admin
> 
> ! Edit /etc/tomcat7/tomcat-users.xml and add the following after and
> before
> sudo vi /etc/tomcat7/tomcat-users.xml
> < role rolename="admin-gui"/>
> < role rolename="manager-gui"/>
> < role rolename="manager-script"/>
> < role rolename="manager-jmx"/>
> < role rolename="manager-status"/>
> < user username="admin" password="admin"
> roles="admin-gui,manager-gui,manager-script,manager-jmx,manager-status"/>
> 
> ! restart tomcat
> sudo /etc/init.d/tomcat restart
> 
> ! Check Tomcat Server and go into manager mode
> 
> ! Deploy Pentaho-reports to tomcat application server
> ! Install Ant
> sudo apt-get install ant
> 
> ! Install subversion
> sudo apt-get install subversion
> 
> mkdir /opt/openerp/ivy
> cd /opt/openerp/ivy
> 
> ! Install Ivy
> svn co https://svn.apache.org/repos/asf/ant/ivy/core/trunk ivy
> ant jar
> sudo cp build/artifact/jars/ivy.jar /usr/share/ant/lib
> 
> ! Extract Pentaho Reports
> 
> cd /opt/openerp
> unzip Pentaho-reports-for-OpenERP-version70.zip
> cd Pentaho-reports-for-OpenERP-version70
> 
> ! Build Java Server for Pentaho Reports
> cd javaserver
> ant war
> 
> ! The output war file “pentaho-reports-for-openerp.war” will be found in
> /opt/openerp/Pentaho-reports-for-OpenERP-version70/java_server/build/jar
> folder.
> 
> ! Deploy “pentaho-reports-for-openerp.war” on Tomcat. If successful, the
> application will show up in Tomcat Manager (URL: http://:8080/manager).
> Follow Tomcat instructions for deploying/installing war file (the options
> are in the Manager).
> ! Pentaho Reports Java Application should now be available in http://
> :8080/pentaho-reports-for-openerp.
> 
> Error: The last step is not working. We get a HTTP 405 error on the URL:
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/WillowIT/Pentaho-reports-for-OpenERP/issues/30.

## 

Saludos
Christopher

**Comment by b-kannan** [comment]
The problem was not due to JRE. Rather it was the result of the misunderstanding of how those reports are accessed or run. I have since been able to integrate the PRD, OpenERP, and Pentaho Java Application Server (standalone using ant launch and using Tomcat container). Thank you.

**Comment by bdunnaway** [comment]
b-kannan, can you please give us a further explanation of how you solved this? I seem to be having the same problem. I've tried both Tomcat7 and the standalone. Neither are working.

**Comment by richard-willdooit** [comment]
@bdunnaway - Can you be more specific.  Have you downloaded from the latest codebase.

**Comment by bdunnaway** [comment]
Okay, for anyone who may be confused, as I was, here is my understanding of how this works:

Please correct me if I am wrong.

Apparently, there is no actual web page you can view in the Tomcat Server or the Pentaho standalone application server. 

So if you attempt to view it, you will get a 405 error. That doesn't mean it's not functioning correctly, because the XmlRpc Servlet is doing what it's supposed to do to allow the OpenERP add-on to work.

I had assumed that because I could not view the page, that there was something wrong. I'm assuming that's what  @b-kannan meant when he said, 

> it was the result of the misunderstanding of how those reports are accessed or run

**Comment by b-kannan** [comment]
@bdunnaway got it right. The Java App Server for Pentaho listens to xmlrpc requests from OpenERP through the Pentaho Addon on OpenERP. So, my expectation to see something up on the browser when connected to Tomcat was incorrect.
