### ISSUE TITLE
[Solved] Failed to invoke method execute ...PentahoRenderer: Failed at query

### ISSUE THREAD

**Issue by jesus-escobedo** [WilldooIT/Pentaho-reports-for-OpenERP#300]
Hi.
  I would like some help on this issue, it may be the similar to other existing issues but the solutions already found do not cause any effect and there are some differences on the exception:

I have Odoo version 8 and Pentaho Reports for OpenERP 8.0.0.1

I am trying to create some reports on xls and pdf format, both resulting on the same exception: 
    Visually when clicking on the print button, a popup window is shown with only these message: **<class 'xmlrpclib.Fault'>,,<traceback object at 0x7fbec4d595f0>** 
    The odoo log shows the following:
`openerp.service.report: Exception: <Fault 0: "Failed to invoke method execute in class com.willowit.reporting.PentahoRenderer: Failed at query: ...` (see attached file to complete exception)
[pentaho error.txt](https://github.com/WilldooIT/Pentaho-reports-for-OpenERP/files/1813132/pentaho.error.txt)

**Comment by richard-willdooit** [comment]
Have you looked at the output from catalina.out - the tomcat log?

**Comment by jesus-escobedo** [comment]
There is no output related to printing the report, just the stop and start up of the tomcat itself, don´t know if this is another problem related or is it a malfunction of tomcat.
Another note: When I accessed to tomcat GUI manager, there is no problem, is stops ad starts correctly and the GUI manager tells me the war /pentaho-reports-for-openerp is running OK, but if I try to access to http://IP_server:8080/pentaho-reports-for-openerp/ it gives me a 405 http status, HTTP method GET is not supported by this URL. 
Any thoughts?

**Comment by jesus-escobedo** [comment]
I´m having doubts on the configuration of the database connection inside the prpt files, mainly on the pwd, I´m using: 
`<data:property name="password">postgres</data:property>`
but I see examples where people use:
`<data:property name="password">encrypted:$0m3thing</data:property>`
**How can I obtain the encryted version of my pwd??**

**Comment by jon-willdooit** [comment]
You need to look at the logfiles for tomcat and/or odoo. The 405 error is
normal; Pentaho doesn't accept GET requests to that URL, only POST.



Kind regards

Jonathan Wilson

*Director of Sales Odoo*

WilldooIT Pty Ltd

*First & only Australian Odoo GOLD partner*
*2017, 2015 & 2013 Odoo Best Partner Asia/Pacific*
*Creators of  Odoo-Pentaho integration project*

"Provide end to end IT solutions to help our clients achieve their desired
objectives and provide growth opportunities for everyone working in the
company to reach their full professional potential"

E: jonathan.wilson@willdooit.com <jonathanw@willdooit.com>

P: +61 3 9135 1900

M: +61  4 000 17 444

10/435 Williamstown Road

Port Melbourne VIC 3207

DISCLAIMER | This electronic message together with any attachments is
confidential. If you are not the recipient, do not copy, disclose, or use
the contents in any way. Please also advise us by e-mail that you have
received this message in error and then please destroy this email and any
of its attachments. WilldooIT Pty. Ltd. is not responsible for any changes
made to this message and/or any attachments after sending by Willdoo IT
Pty. Ltd. WilldooIT Pty. Ltd. use virus scanning software but exclude all
liability for virus or anything similar in this email or attachment.

**Comment by richard-willdooit** [comment]
> There is no output related to printing the report, just the stop and start up of the tomcat itself, don´t know if this is another problem related or is it a malfunction of tomcat.

There is an activity log, though, called catalina.out, which should fill up with lines of activity when it is called.

> http://IP_server:8080/pentaho-reports-for-openerp/ 
It is not accessible via that method - correct.  405 is expected.

Seriously, find catalina.out and "tail" the log file when the report is run.  If nothing comes out, then it is not even getting to the java and your OpenERP settings are really screwed!

The connection from Pentaho back to the database does NOT use what is stored in the PRPT files - it is passed in from the OpenERP settings.  So, again, check that.

**Comment by richard-willdooit** [comment]
@jon-willdooit Beat me by a few seconds!!

**Comment by jon-willdooit** [comment]
This should be the username and password you use when you set postgres up.

Kind regards

Jonathan Wilson

*Director of Sales Odoo*

WilldooIT Pty Ltd

*First & only Australian Odoo GOLD partner*
*2017, 2015 & 2013 Odoo Best Partner Asia/Pacific*
*Creators of  Odoo-Pentaho integration project*

"Provide end to end IT solutions to help our clients achieve their desired
objectives and provide growth opportunities for everyone working in the
company to reach their full professional potential"

E: jonathan.wilson@willdooit.com <jonathanw@willdooit.com>

P: +61 3 9135 1900

M: +61  4 000 17 444

10/435 Williamstown Road

Port Melbourne VIC 3207

DISCLAIMER | This electronic message together with any attachments is
confidential. If you are not the recipient, do not copy, disclose, or use
the contents in any way. Please also advise us by e-mail that you have
received this message in error and then please destroy this email and any
of its attachments. WilldooIT Pty. Ltd. is not responsible for any changes
made to this message and/or any attachments after sending by Willdoo IT
Pty. Ltd. WilldooIT Pty. Ltd. use virus scanning software but exclude all
liability for virus or anything similar in this email or attachment.

**Comment by jesus-escobedo** [comment]
**[SOLVED]** Thank you for your time and help, eventhough I didn´t see any output by "tailing" the catalina.out (maybe there is something missing in the tomcat config), I did change the configuration on OpenERP settings to pentaho (Settings>Technical>Parameters>System Parameters) and updated the pentaho.postgres.host from localhost to the actual IP (eventhough it is its own IP), but other than this I also updated the DB conn in the datasource of the PRPT files, updated the pg_hba.conf file, and restart the tomcat and OpenERP several times.
