### ISSUE TITLE
[7.0] ant launch and/or build fails with fixConfiguration Error

### ISSUE THREAD

**Issue by svenpetersen** [WilldooIT/Pentaho-reports-for-OpenERP#33]
Hello,

I tried running the Java Component with ant launch but got the following Error:

java_server/src/com/willowit/reporting/PentahoRenderer.java:198: error: method fixConfiguration in class PentahoRenderer cannot be applied to given types;
    [javac]               fixConfiguration((Section) sub);
    [javac]               ^
    [javac]   required: Section,HashMap<String,String>,HashMap<String,String>,HashMap<String,?>
    [javac]   found: Section
    [javac]   reason: actual and formal argument lists differ in length
    [javac] Note: /home/conexus/Downloads/Pentaho-reports-for-OpenERP-version70/java_server/src/com/willowit/reporting/PentahoRenderer.java uses unchecked or unsafe operations.

Some arguments missing in Line 198 of PentahoRenderer.java?
Sorry if I'm wrong. I'm not used to Java.

with kind regards,
Sven

**Comment by wenshan-willowit** [comment]
Hi Sven,

When did this happen, during the building process or after "[java] INFO StandaloneReportServer - Accepting requests"?

Besides that, could you please let us know your `OS',`JDK' and `ant' information?

Regards,
Wenshan

**Comment by svenpetersen** [comment]
Hello Wenshan,

thanks for your answer.

It happened during the building process.

Here are the Versions:

Apache Ant(TM) version 1.8.2 compiled on December 3 2011

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.2 LTS"

java version "1.7.0_15"
OpenJDK Runtime Environment (IcedTea7 2.3.7) (7u15-2.3.7-0ubuntu1~12.04)
OpenJDK Server VM (build 23.7-b01, mixed mode)

thanks,
Sven

**Comment by wenshan-willowit** [comment]
@svenpetersen 

Sorry for the trouble, we tried to fix a bug, but caused a new problem.

Please use a slightly older commit:

$ git checkout version70
$ git reset --hard 1ccbc52a0c822a30e605554fb36af6bd411b21bd
$ cd java_server
$ ant launch

Please let me know if you have any problems.
- Wenshan

**Comment by wenshan-willowit** [comment]
@svenpetersen 

We've updated the repo, you should now be able to build the java server from the latest `version70' branch.

Please let me know the result, thanks.

**Comment by svenpetersen** [comment]
perfect, it works.

thank you very much!
