### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by theopensourcerer** [WilldooIT/Pentaho-reports-for-OpenERP#35]
Hi, I just setup the report designer and the java_server in my tomcat6 on Ubuntu 10.04. we are using OpenERP version 7 for testing.

In Catalina.out I am seeing the following messages which seem to prevent my test report from working:

DEBUG ObjectUtilities - Specified class org.pentaho.reporting.libraries.resourceloader.modules.factory.svg.SVGImageFactoryModule cannot be loaded [NOCLASSDEFERROR].
DEBUG ObjectUtilities - Specified class org.pentaho.reporting.libraries.css.parser.StyleRuleFactory cannot be loaded [NOCLASSDEFERROR].
DEBUG ObjectUtilities - Specified class org.pentaho.reporting.libraries.css.parser.StyleSheetFactory cannot be loaded [NOCLASSDEFERROR].
DEBUG ObjectUtilities - Specified class org.pentaho.reporting.libraries.resourceloader.modules.factory.svg.SVGDrawableFactoryModule cannot be loaded [NOCLASSDEFERROR].
DEBUG ObjectUtilities - Specified class org.pentaho.reporting.libraries.resourceloader.modules.cache.ehcache.EHCacheProvider cannot be loaded [NOCLASSDEFERROR].
DEBUG ObjectUtilities - Specified class org.pentaho.reporting.libraries.resourceloader.modules.cache.ehcache.EHCacheProvider cannot be loaded [NOCLASSDEFERROR].
DEBUG ObjectUtilities - Specified class org.pentaho.reporting.libraries.resourceloader.modules.cache.ehcache.EHCacheProvider cannot be loaded [NOCLASSDEFERROR].

Am I missing a jar file or something? I built it using ant as instructed.

**Comment by wenshan-willowit** [comment]
Could you test if it a purchase order (or whatever) can be printed from OpenERP 7.0 using the pentaho-reports module?

**Comment by theopensourcerer** [comment]
Thanks for following up.

Unfortunately it isn't working. I attach a screenshot of the error on OpenERP: 
![pentaho-error](https://f.cloud.github.com/assets/3414988/247715/63fd01d2-8aed-11e2-996c-11e2f7c16ad8.png)

In tomcat's catalina.out it looks like I am actually seeing two separate errors: 

The first looks to me like I can't have the tomcat/webapps/pentaho-reports-for-openerp running on a different machine to OpenERP (it is trying to connect back to the parameters stored for postgres, e.g. localhost...

![pentaho-params](https://f.cloud.github.com/assets/3414988/247707/2a723612-8aed-11e2-8704-3b15d00e92e9.png)

This is how we would like to use it - a different server with the Java/Tomcat applications and one for OpenERP.

The second error looks like the missing dependencies - here is some trace from catalina.out when I request my Pentaho report:

org.pentaho.reporting.libraries.resourceloader.FactoryParameterKey{name=property-expansion}=false}, parent=ResourceKey{schema=org.pentaho.reporting.libraries.resourceloader.loader.raw.RawResourceLoader, identifier=[B@7f22810c, factoryParameters={}, parent=null}}
DEBUG EHCacheModule#CacheLog - Storing created bundle-resource for key: ResourceKey{schema=org.pentaho.reporting.libraries.resourceloader.loader.raw.RawResourceLoader, identifier=[B@3b3adb83, factoryParameters={}, parent=null}
DEBUG Element - master-report: Attribute http://reporting.pentaho.org/namespaces/report-designer/2.0|preview-dialog-bounds is not listed in the metadata.
DEBUG Element - master-report: Attribute http://reporting.pentaho.org/namespaces/report-designer/2.0|zoom is not listed in the metadata.
DEBUG Element - group-footer: Attribute http://reporting.pentaho.org/namespaces/report-designer/2.0|hideInLayoutGUI is not listed in the metadata.
DEBUG Element - group-footer: Attribute http://reporting.pentaho.org/namespaces/report-designer/2.0|visual-height is not listed in the metadata.
DEBUG Element - group-header: Attribute http://reporting.pentaho.org/namespaces/report-designer/2.0|hideInLayoutGUI is not listed in the metadata.
DEBUG Element - group-header: Attribute http://reporting.pentaho.org/namespaces/report-designer/2.0|visual-height is not listed in the metadata.
DEBUG Element - itemband: Attribute http://reporting.pentaho.org/namespaces/report-designer/2.0|visual-height is not listed in the metadata.
DEBUG Element - no-data-band: Attribute http://reporting.pentaho.org/namespaces/report-designer/2.0|hideInLayoutGUI is not listed in the metadata.
DEBUG Element - no-data-band: Attribute http://reporting.pentaho.org/namespaces/report-designer/2.0|visual-height is not listed in the metadata.
DEBUG Element - details-header: Attribute http://reporting.pentaho.org/namespaces/report-designer/2.0|hideInLayoutGUI is not listed in the metadata.
DEBUG Element - details-header: Attribute http://reporting.pentaho.org/namespaces/report-designer/2.0|visual-height is not listed in the metadata.
DEBUG Element - details-footer: Attribute http://reporting.pentaho.org/namespaces/report-designer/2.0|hideInLayoutGUI is not listed in the metadata.
DEBUG Element - details-footer: Attribute http://reporting.pentaho.org/namespaces/report-designer/2.0|visual-height is not listed in the metadata.
DEBUG Element - watermark: Attribute http://reporting.pentaho.org/namespaces/report-designer/2.0|hideInLayoutGUI is not listed in the metadata.
DEBUG Element - watermark: Attribute http://reporting.pentaho.org/namespaces/report-designer/2.0|visual-height is not listed in the metadata.
DEBUG Element - page-footer: Attribute http://reporting.pentaho.org/namespaces/report-designer/2.0|visual-height is not listed in the metadata.
DEBUG Element - page-header: Attribute http://reporting.pentaho.org/namespaces/report-designer/2.0|visual-height is not listed in the metadata.
DEBUG Element - report-footer: Attribute http://reporting.pentaho.org/namespaces/report-designer/2.0|visual-height is not listed in the metadata.
DEBUG Element - report-header: Attribute http://reporting.pentaho.org/namespaces/report-designer/2.0|visual-height is not listed in the metadata.
DEBUG AbstractReportProcessor - 1870956043: Report processing time: Starting: Free: 662904520; Total: 1141309440
ERROR AbstractReportProcessor - 1870956043: Report processing failed.
ERROR PdfReportUtil - Writing PDF failed.

**Comment by andreschenkels** [comment]
The Pentaho module looks to the ip of the xml-rpc in the openerp conf. If its empty IT connects back to localhost.
Change IT to the external address of your openerp server.

Sent from my Windows Phone

**Comment by theopensourcerer** [comment]
Fantastic! That worked . Cheers.

Am closing this issue and thanks again.

**Comment by the9gamer** [comment]
I dont quite get it,
This is the section of the openerp.conf file about xmlrpc:

```
 db_password =openpgpwd
 xmlrpcs = True
 xmlrpcs_interface = 
 syslog = False
 logrotate = True
 xmlrpcs_port = 8071
 test_report_directory = False
 list_db = True
 timezone = False
 xmlrpc_interface = 
 test_file = False
 smtp_password = False
 secure_pkey_file = server.pkey
 xmlrpc_port = 8069 
 workers = 0
 log_level = info
 xmlrpc = True
 admin_passwd = admin
 smtp_port = 25
 smtp_server = localhost
 static_http_url_prefix = None
```

What are the changes you suggest?? and thank you for your time.

**Comment by theopensourcerer** [comment]
xmlrpc_interface = {your host's IP address here} 

(The OpenERP host's IP not the Pentaho server)

**Comment by the9gamer** [comment]
I still have the same error

**Comment by andreschenkels** [comment]
Can you check you’re output of the /var/log/tomcat7/catalina.out perhaps there are some leeds here to solve your problem.

Kind regards,

André Schenkels
ICTSTUDIO
mobiel | +31 6 53250063
email | a.schenkels@ictstudio.eumailto:a.schenkels@ictstudio.eu
[logo]

Van: the9gamer [mailto:notifications@github.com]
Verzonden: vrijdag 14 juni 2013 16:46
Aan: WillowIT/Pentaho-reports-for-OpenERP
CC: André Schenkels - ICTSTUDIO
Onderwerp: Re: [Pentaho-reports-for-OpenERP] Missing dependencies? (#35)

I still have the same error
