### ISSUE TITLE
XMLRPC interface system parameters

### ISSUE THREAD

**Issue by andreschenkels** [WilldooIT/Pentaho-reports-for-OpenERP#37]
If you have more interfaces on your openerp server and want to communicate with Pentaho Report Server the default setting of no xmlrpc config setting = localhost doens't work.
Can you provide a system parameter to set the interface for communication?

**Comment by richard-willdooit** [comment]
Your proposed merge has been accepted, with the proviso that the default is not changed. It should come from the current environment, and if we set it as per your mod, existing sites could potentially stop working.
