### ISSUE TITLE
Error "No connection could be made because the target machine actively refused it" when running Pentaho Reports for OpenERP

### ISSUE THREAD

**Issue by YuliantiLee** [WilldooIT/Pentaho-reports-for-OpenERP#39]
Hi,

I've developed a Pentaho report, and the report runs well in my local openERP. When I tried to run it in my client's server, there's this error:
No connection could be made because the target machine actively refused it

(, error(10061, 'No connection could be made because the target machine actively refused it'), )

I've turned off the firewall and the this error is still occurred.
Do you have any idea how to solve this?

Thanks,
Yuli

**Comment by wenshan-willowit** [comment]
Hi Yulianti,

Can I know that:
1. Is the client server able to produce Pentaho reports other than the one that you developed?
2. How did you deploy Pentaho on the client's server?

Regards,
Wenshan

**Comment by mohammedaghiourly** [comment]
hi all:
I have the same problem, anybody can help me plz?

**Comment by YuliantiLee** [comment]
Hi Mohammed,

I don't know if this will work on your side, but my error is disappear after I restart service and server.

Regards,
Yuli

**Comment by the9gamer** [comment]
Hi all,
I have the same problem, have anyone found a solution??

**Comment by theopensourcerer** [comment]
If Pentaho and OpenERP are on different servers please note the following comment: https://github.com/WillowIT/Pentaho-reports-for-OpenERP/issues/35#issuecomment-14763420

**Comment by the9gamer** [comment]
I dont quite get it,
This is the section of the openerp.conf file about xmlrpc:

   db_password =openpgpwd
   xmlrpcs = True
   xmlrpcs_interface = 
   syslog = False
   logrotate = True
   xmlrpcs_port = 8071
   test_report_directory = False
   list_db = True
   timezone = False
   xmlrpc_interface = 
   test_file = False
   smtp_password = False
   secure_pkey_file = server.pkey
   xmlrpc_port = 8069 
   workers = 0
   log_level = info
   xmlrpc = True
   admin_passwd = admin
   smtp_port = 25
   smtp_server = localhost
   static_http_url_prefix = None

What are the changes you suggest?? and thank you for your time.

**Comment by richard-willdooit** [comment]
Thanks for those that look at this.  I assume the issues are now resolved.  The latest merges now allow this to be defined in ir.config.
