### ISSUE TITLE
Replace default reports in OpenERP

### ISSUE THREAD

**Issue by bretif** [WilldooIT/Pentaho-reports-for-OpenERP#41]
I am using pentaho reports and it is working great. I create them in openerp ui without any problems. I would like to define my pentaho reports in XML file like "normal report":

```
<report id="report_shipping"
model="stock.picking"
name="sale.shipping"
multi="True"
rml="delivery/report/shipping.rml"
string="Delivery order"/>
```

My goal is to redefine the XML ID of standard report to replace them with pentaho report.

Is it possible? Is there another solution to do it?

**Comment by richard-willdooit** [comment]
Hello,

Sorry about the delay in responding.

Yes, it is possible to use the Pentaho Report as a replacement to the standard report.  The key is the service name.

If you define your Pentaho Report in OpenERP with the same Service Name as the standard action, (and rename the standard action's Service Name to avoid conflict), then all should be fine.

Another way, a little nasty but effective, is to use pgadmin or some-such to modify the ir_act_report_xml table and set "is_pentaho_report" to true for the desired action.  It can now be edited through the standard OpenERP interface as a pentaho report.

There has been a thought of an easier means to switch an action from non-Pentaho to Pentaho....

**Comment by richard-willdooit** [comment]
This last committed change (version70 only) allows the action to be modified in-situ.

**Comment by bretif** [comment]
Thanks for your answer. I succesfully replace standard report by pentaho report in the GUI.
However I am not able to it it through xml. Then if I update my db with -all, all standard reports are back.

If I try to replace sale.order:



```
<report id="sale.sale_order.pentaho"
        model="sale.order"
        name="sale.order"
        file="psispec-addons/psi_report/reports/sale.order.prpt"
        report_type="webkit"
        is_pentaho_report="True"
        pentaho_report_output_type="pdf" />
```

I get an error:  "Invalid attribute is_pentaho_report for element report"

It is not a huge issue, but It would be great in the feature to defaine report through XML.

Thanks again for the great job you did!

Bertrand

**Comment by flotho** [comment]
Hy,

Did you add the pentaho_report_addon as dependency in your openerp module?

**Comment by bretif** [comment]
Hi,

Yes pentaho_report_addon has an entry in depends in my __openerp_.py 

Here the error I get:
ERROR:RELAXNGV:RELAXNG_ERR_INVALIDATTR: Invalid attribute is_pentaho_report for element report

**Comment by richard-willdooit** [comment]
Yes, this problem is relating to the xml parser.  In our modules, we define the actions as standard actions and overwrite those actions:

```
<data noupdate="1">  <!-- 'noupdate' means existing data is *not* overwritten when module is updated -->
    <record id="purchase.report_purchase_order" model="ir.actions.report.xml">
        <field name="is_pentaho_report" eval="True"/>
        <field name="pentaho_report_model_id" ref="purchase.model_purchase_order"/>
        <field name="pentaho_report_output_type">pdf</field>
        <field name="pentaho_filename">xxx_reports/layouts/purchase-order.prpt</field>
        <field name="pentaho_load_file" eval="True"/>
    </record>
</data>
```

If someone changes the rng definition for the xml parsing, then definition using the other method will be possible.  But this method is more than satisfactory, we believe.

**Comment by bretif** [comment]
Thanks a lot for your help.
It is now working.
