### ISSUE TITLE
Pentaho Reports for OpenERP won't show Chinese Fonts.

### ISSUE THREAD

**Issue by YuliantiLee** [WilldooIT/Pentaho-reports-for-OpenERP#42]
Hi,

My developer designed a report in pentaho report designer which some of the words using Chinese character. When she printed preview in PRD, the Chinese words appeared. But when she tried to view it in OpenERP (report format is PDF), only those with Chinese character disappeared from report.

Is it the problem of the adobe reader or pentaho? Do you guys have any solution for this case?

FYI, She'd already installed adobe reader X and also Chinese font package for adobe reader but it still won't come out. And one more thing, she used "Sim sun" font for this report.

This is how the report showed in Pentaho Print Preview:
![pentaho](https://f.cloud.github.com/assets/4200100/470023/feb2afca-b6e8-11e2-8093-e2dc7544ad42.jpg)

This is how the report showed from OpenERP:
![openerp](https://f.cloud.github.com/assets/4200100/470037/3fb30e02-b6e9-11e2-99e4-84d0dc92af71.jpg)

Regards,
Yulianti Lee

**Comment by richard-willdooit** [comment]
Please check that all required fonts are installed on the server that is running Tomcat.  They need to reside in /usr/share/fonts.
