### ISSUE TITLE
Pentaho OpenERP context parameter in another paramter query

### ISSUE THREAD

**Issue by jjscarafia** [WilldooIT/Pentaho-reports-for-OpenERP#43]
First of all congratulations for the module. 
We are working on OERP 7. 
2 queries:
- Main query
- Query for paramter A filtered by user_id
  2 paramters:
- Paramter A
- user_id

User_id comes from the context ok (for example showing it on the report), but can't be used in the query of a parameter
Thanks!

**Comment by richard-willdooit** [comment]
I understand the issue, and it is valid.  We will consider this for inclusion when we upgrade the interface for Pentaho 5.

**Comment by lxdorney** [comment]
Hi, is there any bug for Pentaho-reports-for-OpenERP after I installed pentaho-reports I can't see under Settings/Actions the sub menu of Pentaho Reports. is there any missed configuration?
I successfully installed addons with no errors.

I don't know if this is the right link to post this issue

Im using OpenERP 7

thanks

**Comment by flotho** [comment]
Hy,

Plesae, try to not make duplicates.
The answer is here : https://github.com/WillowIT/Pentaho-reports-for-OpenERP/pull/50#issuecomment-35181533
