### ISSUE TITLE
Pentaho Reports won't use font other than Helvetica when printed from OpenERP

### ISSUE THREAD

**Issue by b-kannan** [WilldooIT/Pentaho-reports-for-OpenERP#45]
I am using Futura Std Book font in my prpt. PDF written by PRD uses the font but the PDF written when run from OpenERP uses Helvetica font instead.

PRD output:
![image](https://f.cloud.github.com/assets/3299778/502861/97a87ef2-bcbc-11e2-969d-9f9eb7e7ed04.png)

Pentaho-OpenERP output:

![image](https://f.cloud.github.com/assets/3299778/502864/b44c24d2-bcbc-11e2-9c76-84605f80faf6.png)

**Comment by richard-willdooit** [comment]
Please check that all required fonts are installed on the server that is running Tomcat.  They need to reside in /usr/share/fonts.
