### ISSUE TITLE
Pentaho Desinger 4.0 (TRUNK)

### ISSUE THREAD

**Issue by RickHunterEc** [WilldooIT/Pentaho-reports-for-OpenERP#46]
Hi, have you planned to migrate the module to PRD 4.0? Crosstab is a new function in PRD 4.0. Great feature for OpenERP Reports.
Thanks.

**Comment by richard-willdooit** [comment]
We will not be migrating to version 4.  However, there are plans to upgrade when PRD 5.0 is released.  Stay tuned.
