### ISSUE TITLE
Print barcode from OpenERP - barbecue library missing

### ISSUE THREAD

**Issue by bretif** [WilldooIT/Pentaho-reports-for-OpenERP#47]
barbecue-1.5-beta1.jar need to be included in pentaho-reports-for-openerp.war
I was not able to print barcode from openerp otherwise it was working properly in report designer.

I copied the library barbecue-1.5-beta1.jar in ${tomcat}/webapps/pentaho-reports-for-openerp/WEB-INF/lib and it is now working.

**Comment by bretif** [comment]
I get also the same issue by using BeginWith function.
In order to get it working, I added pentaho-metadata-3.4.5.jar in ${tomcat}/webapps/pentaho-reports-for-openerp/WEB-INF/lib
I think it should be added to pentaho-reports-for-openerp.war

**Comment by flotho** [comment]
+1
