### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by djizno** [WilldooIT/Pentaho-reports-for-OpenERP#48]
Hi,

Got 3 openERP databases on the same server (OpenERP v7).

Sometimes, got an error printing pentaho reports "No data returned". Looking catalina.out, the error is "java.lang.Exception: Incorrect username and/or password.  Login Failed.".

To avoid this issue : 
1. I need to modify your core.py addon file to put real value instead of variables (db, login, password, host) 
2. delete python compiled files and resatrt the server
3. print a pentaho report -> OK
4. modify again core.py to comment real values and put back variables

Any suggestion for this issue cause it's not a real fix for production system..

**Comment by flotho** [comment]
Hy,

Maybe, you could have a look in the cron jobs of OpenERP.
Probably you could be able to flush the values stored in the session files or stuff like that.
Maybe a trigger each time a report is submitted to refresh the values could be a great idea.

**Comment by flotho** [comment]
did you checked the parameter in the user interface, are you sure that no space has been type in in user/password values
Did it happened on all your db or just one?
