### ISSUE TITLE
Please add information about which OpenERP version this is for

### ISSUE THREAD

**Issue by OE-Tester** [WilldooIT/Pentaho-reports-for-OpenERP#53]
Hi, could you please add information about which version of OpenERP this tool is for? Thanks!

**Comment by theopensourcerer** [comment]
Huh? There are three clearly labelled branches: 6.0, 6.1 & 7.0

**Comment by ghost** [comment]
Its a bot, same question posted here -
https://github.com/enapps/ea_import/issues/6#issuecomment-20146669

**Comment by OE-Tester** [comment]
No, I am not a bot - in this case here I did not see the branches, I was just reading the description. 

We all know it does make sense to automatically add $version if one writes about software, unfortunately I see many blog posts and software projects in OpenERP world where people seem to forget about that, what makes research about the OpenERP ecosystem a little but irritating - but this project seems to be the positive exception! Thank you very much for your attention and sorry for not realizing the $version branches at first glance.

**Comment by ghost** [comment]
Join the club OE Tester!

It is unfortunate that OpenERP doesn’t plan the core to be compatible with
modules from previous versions, so as much as it is frustrating for you to
review, it is even more frustrating having to maintain more than one
version of a module even if that means the whole difference is a few lines
of code!

**Comment by OE-Tester** [comment]
backwards-compatibility is for people with hobbies :)
