### ISSUE TITLE
How to pass context

### ISSUE THREAD

**Issue by andhit-r** [WilldooIT/Pentaho-reports-for-OpenERP#54]
First off all .. Great work guys. One thing though. Some  objects use  context value to calculate function field (e.g : account.account to compute balance field or product.product to compute qty). How can we do it with pentaho?

**Comment by richard-willdooit** [comment]
Hello,

We have discussed this, but we will not be adding new functionality like this to the current interface.  We will re-assess and may consider allowing for this when we port for Pentaho version 5.

**Comment by richard-willdooit** [comment]
A pull request was merged which passes the context in.  It will arrive as a dictionary, and you will need to pull the context values out, and this will need some specialised coding.  But it is being passed in, now.
