### ISSUE TITLE
Imprimir archivo en excel

### ISSUE THREAD

**Issue by amagallanesm** [WilldooIT/Pentaho-reports-for-OpenERP#58]
(<class 'xmlrpclib.Fault'>, <Fault 0: 'Failed to invoke method execute in class com.willowit.reporting.PentahoRenderer: Could not initialize class org.pentaho.reporting.engine.classic.core.modules.output.table.xls.helper.StaticExcelColorSupport'>, <traceback object at 0x7f71947a6518>)

**Comment by richard-willdooit** [comment]
??
