### ISSUE TITLE
How to retrieve image from database in pentaho sql based reprot

### ISSUE THREAD

**Issue by kl-adonze** [WilldooIT/Pentaho-reports-for-OpenERP#70]
Hi , i am cretaing an SQL based report and written a query to retrieve the image from postgresql database, the images are not getting displayed when i call report from openerp but images are getting displayed in pentaho report designer , how the fix the issue

**Comment by flotho** [comment]
Hy,

Actually there is no issue, only a tip to follow here : https://github.com/WillowIT/Pentaho-reports-for-OpenERP/wiki/Displaying-images-for-SQL-Reports
It solved my problems.

regards

**Comment by kl-adonze** [comment]
Ok thanks 
Regards
