### ISSUE TITLE
Very slow when print many record

### ISSUE THREAD

**Issue by dntq83** [WilldooIT/Pentaho-reports-for-OpenERP#74]
Very slow when print many record, iReport faster than pentaho when print many record

**Comment by richard-willdooit** [comment]
Sorry, but we need far more information to consider this.

Generally, we have received positive feedback, and personally have seen, excellent throughput rates for data.

Object based reports will be slower than those based on SQL queries, but if they are particularly slow, then there may be issues with the way you have defined your data sources, as well as possible inefficiencies in your connector definitions.

**Comment by dntq83** [comment]
Thank you for your reply.

I'm create report using ORM in Pentaho and iReport, same object, same server. But when print Pentaho is slower than ireport (Same record). I checked log on OpenERP Server, pentaho many request to OpenERP and iReport request only one time.
