### ISSUE TITLE
Pentaho Menu

### ISSUE THREAD

**Issue by karimha** [WilldooIT/Pentaho-reports-for-OpenERP#86]
Hello
I have a question in Pentaho in Version 7 there is no Menu under Settings/Technical/Actions/...
i edited the code in the view (report_xml_view.xml) by adding the menu and it work.
are forget to add it or there is an other way to install it.
Thank you

**Comment by karimha** [comment]
```
    <menuitem action="ir_action_report_pentaho_report" id="menu_ir_action_report_pentaho_report" parent="base.next_id_6"/> 
 and the 3 actions
```

**Comment by richard-willdooit** [comment]
The latest version no longer needs a separate menu entry for action maintenance.  The current way to edit Pentaho Report actions is through the standard Report Actions where a checkbox has been added to distinguish Pentaho reports.

**Comment by richard-willdooit** [comment]
Sorry, should have included the menu path:

```
Settings/Technical/Low Level Objects/Actions/Reports
```
