### ISSUE TITLE
Cache issues?

### ISSUE THREAD

**Issue by flotho** [WilldooIT/Pentaho-reports-for-OpenERP#87]
Hy,

I'm having some stranges behaviour while printing.
I generate a report form openerp then I change something in the order and then reprint. Nothing changed.
Yet, I print the same order from PRD, same release, same database and the modifications have been kept.
Is there any cache issue or conf to set in the java module?
Regards

**Comment by richard-willdooit** [comment]
Are you sure that the reprint has not printed the version that was saved in the Document Management System?  We have not encountered this sort of issue before, ourselves.

**Comment by flotho** [comment]
yes you were right.

Sorry for late answer
