### ISSUE TITLE
number format localisation in message type

### ISSUE THREAD

**Issue by Solgema** [WilldooIT/Pentaho-reports-for-OpenERP#93]
Hello!

In a fr_CH environment,
If I have a number field with value 100 and I set format to #,###.00 I get 100.00
If I set the same in a message field like $(value, number, #,###.00) I get 100,00 with a comma as separator which is not localizated. (I shoud get 100.00 also)

Thank you!

Fabien

**Comment by richard-willdooit** [comment]
I suspect this is more a Pentaho question, and nothing to do with our integration module.  I assume the same problem occurs if you print the report from the Report Designer?  This issue would best be addressed in a Pentaho forum.

**Comment by flotho** [comment]
did you have a look to the #205
