### ISSUE TITLE
Improvement - Context locale from partner

### ISSUE THREAD

**Issue by Solgema** [WilldooIT/Pentaho-reports-for-OpenERP#98]
The context locale (lang + tz) is taken from the user who is doing the report action.

I some cases (for ex. with invoices) the lang shoud be the invoce's customer (account.invoice.partner_id).

So maybe it should be possible in the report configuration to choose from where the report gets it's locale.

Thank you

**Comment by richard-willdooit** [comment]
However, if the report is run for more than 1 partner, the partner changes from one invoice to the next.  Therefore, your query should handle the changing partner_ids and pull what it needs from the appropriate partner record, not the calling procedure.
